# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .secret_store_status import SecretStoreStatus


class SecretStore(UniversalBaseModel):
    id: typing.Optional[str] = None
    organization_id: typing.Optional[str] = None
    workspace_id: typing.Optional[str] = None
    name: typing.Optional[str] = None
    store_key: typing.Optional[str] = pydantic.Field(default=None)
    """
    URL-safe slug derived from the store name.
    """

    description: typing.Optional[str] = None
    status: typing.Optional[SecretStoreStatus] = None
    created_at: typing.Optional[dt.datetime] = None
    updated_at: typing.Optional[dt.datetime] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
