# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class VmMetrics(UniversalBaseModel):
    cpu_usage_percent: typing.Optional[float] = None
    memory_usage_percent: typing.Optional[float] = None
    disk_read_bytes: typing.Optional[int] = None
    disk_write_bytes: typing.Optional[int] = None
    network_in_bytes: typing.Optional[int] = None
    network_out_bytes: typing.Optional[int] = None
    collected_at: typing.Optional[dt.datetime] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
