# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.firewall_attachment import FirewallAttachment
from ..types.firewall_group import FirewallGroup
from ..types.firewall_rule_fields_action import FirewallRuleFieldsAction
from ..types.firewall_rule_fields_direction import FirewallRuleFieldsDirection
from ..types.firewall_rule_fields_protocol import FirewallRuleFieldsProtocol
from .raw_client import AsyncRawFirewallsClient, RawFirewallsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class FirewallsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawFirewallsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawFirewallsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawFirewallsClient
        """
        return self._raw_client

    def list_firewall_groups(
        self, *, workspace_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[FirewallGroup]:
        """
        Parameters
        ----------
        workspace_id : str
            The workspace ID to scope this request to.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[FirewallGroup]
            Firewall groups returned successfully.

        Examples
        --------
        from ibee import Ibee

        client = Ibee(
            token="YOUR_TOKEN",
        )
        client.firewalls.list_firewall_groups(
            workspace_id="workspace_id",
        )
        """
        _response = self._raw_client.list_firewall_groups(workspace_id=workspace_id, request_options=request_options)
        return _response.data

    def create_firewall_group(
        self,
        *,
        workspace_id: str,
        name: str,
        description: typing.Optional[str] = OMIT,
        is_default: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FirewallGroup:
        """
        Parameters
        ----------
        workspace_id : str
            The workspace ID to scope this request to.

        name : str

        description : typing.Optional[str]

        is_default : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FirewallGroup
            Firewall group created successfully.

        Examples
        --------
        from ibee import Ibee

        client = Ibee(
            token="YOUR_TOKEN",
        )
        client.firewalls.create_firewall_group(
            workspace_id="workspace_id",
            name="name",
        )
        """
        _response = self._raw_client.create_firewall_group(
            workspace_id=workspace_id,
            name=name,
            description=description,
            is_default=is_default,
            request_options=request_options,
        )
        return _response.data

    def get_firewall_group(
        self, firewall_group_id: str, *, workspace_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> FirewallGroup:
        """
        Parameters
        ----------
        firewall_group_id : str
            Firewall group ID.

        workspace_id : str
            The workspace ID to scope this request to.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FirewallGroup
            Firewall group returned successfully.

        Examples
        --------
        from ibee import Ibee

        client = Ibee(
            token="YOUR_TOKEN",
        )
        client.firewalls.get_firewall_group(
            firewall_group_id="firewall_group_id",
            workspace_id="workspace_id",
        )
        """
        _response = self._raw_client.get_firewall_group(
            firewall_group_id, workspace_id=workspace_id, request_options=request_options
        )
        return _response.data

    def delete_firewall_group(
        self, firewall_group_id: str, *, workspace_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Parameters
        ----------
        firewall_group_id : str
            Firewall group ID.

        workspace_id : str
            The workspace ID to scope this request to.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from ibee import Ibee

        client = Ibee(
            token="YOUR_TOKEN",
        )
        client.firewalls.delete_firewall_group(
            firewall_group_id="firewall_group_id",
            workspace_id="workspace_id",
        )
        """
        _response = self._raw_client.delete_firewall_group(
            firewall_group_id, workspace_id=workspace_id, request_options=request_options
        )
        return _response.data

    def create_firewall_rule(
        self,
        firewall_group_id: str,
        *,
        workspace_id: str,
        description: typing.Optional[str] = OMIT,
        direction: typing.Optional[FirewallRuleFieldsDirection] = OMIT,
        protocol: typing.Optional[FirewallRuleFieldsProtocol] = OMIT,
        port_start: typing.Optional[int] = OMIT,
        port_end: typing.Optional[int] = OMIT,
        remote_targets: typing.Optional[typing.Sequence[str]] = OMIT,
        action: typing.Optional[FirewallRuleFieldsAction] = OMIT,
        priority: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FirewallGroup:
        """
        Parameters
        ----------
        firewall_group_id : str
            Firewall group ID.

        workspace_id : str
            The workspace ID to scope this request to.

        description : typing.Optional[str]

        direction : typing.Optional[FirewallRuleFieldsDirection]

        protocol : typing.Optional[FirewallRuleFieldsProtocol]

        port_start : typing.Optional[int]

        port_end : typing.Optional[int]

        remote_targets : typing.Optional[typing.Sequence[str]]

        action : typing.Optional[FirewallRuleFieldsAction]

        priority : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FirewallGroup
            Firewall rule added successfully.

        Examples
        --------
        from ibee import Ibee

        client = Ibee(
            token="YOUR_TOKEN",
        )
        client.firewalls.create_firewall_rule(
            firewall_group_id="firewall_group_id",
            workspace_id="workspace_id",
        )
        """
        _response = self._raw_client.create_firewall_rule(
            firewall_group_id,
            workspace_id=workspace_id,
            description=description,
            direction=direction,
            protocol=protocol,
            port_start=port_start,
            port_end=port_end,
            remote_targets=remote_targets,
            action=action,
            priority=priority,
            request_options=request_options,
        )
        return _response.data

    def delete_firewall_rule(
        self,
        firewall_group_id: str,
        firewall_rule_id: str,
        *,
        workspace_id: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FirewallGroup:
        """
        Parameters
        ----------
        firewall_group_id : str
            Firewall group ID.

        firewall_rule_id : str
            Firewall rule ID.

        workspace_id : str
            The workspace ID to scope this request to.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FirewallGroup
            Firewall rule deleted successfully.

        Examples
        --------
        from ibee import Ibee

        client = Ibee(
            token="YOUR_TOKEN",
        )
        client.firewalls.delete_firewall_rule(
            firewall_group_id="firewall_group_id",
            firewall_rule_id="firewall_rule_id",
            workspace_id="workspace_id",
        )
        """
        _response = self._raw_client.delete_firewall_rule(
            firewall_group_id, firewall_rule_id, workspace_id=workspace_id, request_options=request_options
        )
        return _response.data

    def update_firewall_rule(
        self,
        firewall_group_id: str,
        firewall_rule_id: str,
        *,
        workspace_id: str,
        enabled: typing.Optional[bool] = OMIT,
        description: typing.Optional[str] = OMIT,
        direction: typing.Optional[FirewallRuleFieldsDirection] = OMIT,
        protocol: typing.Optional[FirewallRuleFieldsProtocol] = OMIT,
        port_start: typing.Optional[int] = OMIT,
        port_end: typing.Optional[int] = OMIT,
        remote_targets: typing.Optional[typing.Sequence[str]] = OMIT,
        action: typing.Optional[FirewallRuleFieldsAction] = OMIT,
        priority: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FirewallGroup:
        """
        Parameters
        ----------
        firewall_group_id : str
            Firewall group ID.

        firewall_rule_id : str
            Firewall rule ID.

        workspace_id : str
            The workspace ID to scope this request to.

        enabled : typing.Optional[bool]

        description : typing.Optional[str]

        direction : typing.Optional[FirewallRuleFieldsDirection]

        protocol : typing.Optional[FirewallRuleFieldsProtocol]

        port_start : typing.Optional[int]

        port_end : typing.Optional[int]

        remote_targets : typing.Optional[typing.Sequence[str]]

        action : typing.Optional[FirewallRuleFieldsAction]

        priority : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FirewallGroup
            Firewall rule updated successfully.

        Examples
        --------
        from ibee import Ibee

        client = Ibee(
            token="YOUR_TOKEN",
        )
        client.firewalls.update_firewall_rule(
            firewall_group_id="firewall_group_id",
            firewall_rule_id="firewall_rule_id",
            workspace_id="workspace_id",
        )
        """
        _response = self._raw_client.update_firewall_rule(
            firewall_group_id,
            firewall_rule_id,
            workspace_id=workspace_id,
            enabled=enabled,
            description=description,
            direction=direction,
            protocol=protocol,
            port_start=port_start,
            port_end=port_end,
            remote_targets=remote_targets,
            action=action,
            priority=priority,
            request_options=request_options,
        )
        return _response.data

    def list_firewall_group_attachments(
        self,
        firewall_group_id: str,
        *,
        workspace_id: str,
        limit: typing.Optional[int] = None,
        skip: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[FirewallAttachment]:
        """
        Parameters
        ----------
        firewall_group_id : str
            Firewall group ID.

        workspace_id : str
            The workspace ID to scope this request to.

        limit : typing.Optional[int]
            Maximum number of records to return.

        skip : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[FirewallAttachment]
            Firewall attachments returned successfully.

        Examples
        --------
        from ibee import Ibee

        client = Ibee(
            token="YOUR_TOKEN",
        )
        client.firewalls.list_firewall_group_attachments(
            firewall_group_id="firewall_group_id",
            workspace_id="workspace_id",
        )
        """
        _response = self._raw_client.list_firewall_group_attachments(
            firewall_group_id, workspace_id=workspace_id, limit=limit, skip=skip, request_options=request_options
        )
        return _response.data

    def attach_firewall_group(
        self,
        firewall_group_id: str,
        *,
        workspace_id: str,
        vm_id: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FirewallGroup:
        """
        Parameters
        ----------
        firewall_group_id : str
            Firewall group ID.

        workspace_id : str
            The workspace ID to scope this request to.

        vm_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FirewallGroup
            VM attached successfully.

        Examples
        --------
        from ibee import Ibee

        client = Ibee(
            token="YOUR_TOKEN",
        )
        client.firewalls.attach_firewall_group(
            firewall_group_id="firewall_group_id",
            workspace_id="workspace_id",
            vm_id="vm_id",
        )
        """
        _response = self._raw_client.attach_firewall_group(
            firewall_group_id, workspace_id=workspace_id, vm_id=vm_id, request_options=request_options
        )
        return _response.data

    def detach_firewall_group(
        self,
        firewall_group_id: str,
        vm_id: str,
        *,
        workspace_id: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FirewallGroup:
        """
        Parameters
        ----------
        firewall_group_id : str
            Firewall group ID.

        vm_id : str
            Virtual machine ID.

        workspace_id : str
            The workspace ID to scope this request to.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FirewallGroup
            VM detached successfully.

        Examples
        --------
        from ibee import Ibee

        client = Ibee(
            token="YOUR_TOKEN",
        )
        client.firewalls.detach_firewall_group(
            firewall_group_id="firewall_group_id",
            vm_id="vm_id",
            workspace_id="workspace_id",
        )
        """
        _response = self._raw_client.detach_firewall_group(
            firewall_group_id, vm_id, workspace_id=workspace_id, request_options=request_options
        )
        return _response.data


class AsyncFirewallsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawFirewallsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawFirewallsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawFirewallsClient
        """
        return self._raw_client

    async def list_firewall_groups(
        self, *, workspace_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[FirewallGroup]:
        """
        Parameters
        ----------
        workspace_id : str
            The workspace ID to scope this request to.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[FirewallGroup]
            Firewall groups returned successfully.

        Examples
        --------
        import asyncio

        from ibee import AsyncIbee

        client = AsyncIbee(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.firewalls.list_firewall_groups(
                workspace_id="workspace_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_firewall_groups(
            workspace_id=workspace_id, request_options=request_options
        )
        return _response.data

    async def create_firewall_group(
        self,
        *,
        workspace_id: str,
        name: str,
        description: typing.Optional[str] = OMIT,
        is_default: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FirewallGroup:
        """
        Parameters
        ----------
        workspace_id : str
            The workspace ID to scope this request to.

        name : str

        description : typing.Optional[str]

        is_default : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FirewallGroup
            Firewall group created successfully.

        Examples
        --------
        import asyncio

        from ibee import AsyncIbee

        client = AsyncIbee(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.firewalls.create_firewall_group(
                workspace_id="workspace_id",
                name="name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_firewall_group(
            workspace_id=workspace_id,
            name=name,
            description=description,
            is_default=is_default,
            request_options=request_options,
        )
        return _response.data

    async def get_firewall_group(
        self, firewall_group_id: str, *, workspace_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> FirewallGroup:
        """
        Parameters
        ----------
        firewall_group_id : str
            Firewall group ID.

        workspace_id : str
            The workspace ID to scope this request to.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FirewallGroup
            Firewall group returned successfully.

        Examples
        --------
        import asyncio

        from ibee import AsyncIbee

        client = AsyncIbee(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.firewalls.get_firewall_group(
                firewall_group_id="firewall_group_id",
                workspace_id="workspace_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_firewall_group(
            firewall_group_id, workspace_id=workspace_id, request_options=request_options
        )
        return _response.data

    async def delete_firewall_group(
        self, firewall_group_id: str, *, workspace_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Parameters
        ----------
        firewall_group_id : str
            Firewall group ID.

        workspace_id : str
            The workspace ID to scope this request to.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from ibee import AsyncIbee

        client = AsyncIbee(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.firewalls.delete_firewall_group(
                firewall_group_id="firewall_group_id",
                workspace_id="workspace_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_firewall_group(
            firewall_group_id, workspace_id=workspace_id, request_options=request_options
        )
        return _response.data

    async def create_firewall_rule(
        self,
        firewall_group_id: str,
        *,
        workspace_id: str,
        description: typing.Optional[str] = OMIT,
        direction: typing.Optional[FirewallRuleFieldsDirection] = OMIT,
        protocol: typing.Optional[FirewallRuleFieldsProtocol] = OMIT,
        port_start: typing.Optional[int] = OMIT,
        port_end: typing.Optional[int] = OMIT,
        remote_targets: typing.Optional[typing.Sequence[str]] = OMIT,
        action: typing.Optional[FirewallRuleFieldsAction] = OMIT,
        priority: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FirewallGroup:
        """
        Parameters
        ----------
        firewall_group_id : str
            Firewall group ID.

        workspace_id : str
            The workspace ID to scope this request to.

        description : typing.Optional[str]

        direction : typing.Optional[FirewallRuleFieldsDirection]

        protocol : typing.Optional[FirewallRuleFieldsProtocol]

        port_start : typing.Optional[int]

        port_end : typing.Optional[int]

        remote_targets : typing.Optional[typing.Sequence[str]]

        action : typing.Optional[FirewallRuleFieldsAction]

        priority : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FirewallGroup
            Firewall rule added successfully.

        Examples
        --------
        import asyncio

        from ibee import AsyncIbee

        client = AsyncIbee(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.firewalls.create_firewall_rule(
                firewall_group_id="firewall_group_id",
                workspace_id="workspace_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_firewall_rule(
            firewall_group_id,
            workspace_id=workspace_id,
            description=description,
            direction=direction,
            protocol=protocol,
            port_start=port_start,
            port_end=port_end,
            remote_targets=remote_targets,
            action=action,
            priority=priority,
            request_options=request_options,
        )
        return _response.data

    async def delete_firewall_rule(
        self,
        firewall_group_id: str,
        firewall_rule_id: str,
        *,
        workspace_id: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FirewallGroup:
        """
        Parameters
        ----------
        firewall_group_id : str
            Firewall group ID.

        firewall_rule_id : str
            Firewall rule ID.

        workspace_id : str
            The workspace ID to scope this request to.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FirewallGroup
            Firewall rule deleted successfully.

        Examples
        --------
        import asyncio

        from ibee import AsyncIbee

        client = AsyncIbee(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.firewalls.delete_firewall_rule(
                firewall_group_id="firewall_group_id",
                firewall_rule_id="firewall_rule_id",
                workspace_id="workspace_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_firewall_rule(
            firewall_group_id, firewall_rule_id, workspace_id=workspace_id, request_options=request_options
        )
        return _response.data

    async def update_firewall_rule(
        self,
        firewall_group_id: str,
        firewall_rule_id: str,
        *,
        workspace_id: str,
        enabled: typing.Optional[bool] = OMIT,
        description: typing.Optional[str] = OMIT,
        direction: typing.Optional[FirewallRuleFieldsDirection] = OMIT,
        protocol: typing.Optional[FirewallRuleFieldsProtocol] = OMIT,
        port_start: typing.Optional[int] = OMIT,
        port_end: typing.Optional[int] = OMIT,
        remote_targets: typing.Optional[typing.Sequence[str]] = OMIT,
        action: typing.Optional[FirewallRuleFieldsAction] = OMIT,
        priority: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FirewallGroup:
        """
        Parameters
        ----------
        firewall_group_id : str
            Firewall group ID.

        firewall_rule_id : str
            Firewall rule ID.

        workspace_id : str
            The workspace ID to scope this request to.

        enabled : typing.Optional[bool]

        description : typing.Optional[str]

        direction : typing.Optional[FirewallRuleFieldsDirection]

        protocol : typing.Optional[FirewallRuleFieldsProtocol]

        port_start : typing.Optional[int]

        port_end : typing.Optional[int]

        remote_targets : typing.Optional[typing.Sequence[str]]

        action : typing.Optional[FirewallRuleFieldsAction]

        priority : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FirewallGroup
            Firewall rule updated successfully.

        Examples
        --------
        import asyncio

        from ibee import AsyncIbee

        client = AsyncIbee(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.firewalls.update_firewall_rule(
                firewall_group_id="firewall_group_id",
                firewall_rule_id="firewall_rule_id",
                workspace_id="workspace_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_firewall_rule(
            firewall_group_id,
            firewall_rule_id,
            workspace_id=workspace_id,
            enabled=enabled,
            description=description,
            direction=direction,
            protocol=protocol,
            port_start=port_start,
            port_end=port_end,
            remote_targets=remote_targets,
            action=action,
            priority=priority,
            request_options=request_options,
        )
        return _response.data

    async def list_firewall_group_attachments(
        self,
        firewall_group_id: str,
        *,
        workspace_id: str,
        limit: typing.Optional[int] = None,
        skip: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[FirewallAttachment]:
        """
        Parameters
        ----------
        firewall_group_id : str
            Firewall group ID.

        workspace_id : str
            The workspace ID to scope this request to.

        limit : typing.Optional[int]
            Maximum number of records to return.

        skip : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[FirewallAttachment]
            Firewall attachments returned successfully.

        Examples
        --------
        import asyncio

        from ibee import AsyncIbee

        client = AsyncIbee(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.firewalls.list_firewall_group_attachments(
                firewall_group_id="firewall_group_id",
                workspace_id="workspace_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_firewall_group_attachments(
            firewall_group_id, workspace_id=workspace_id, limit=limit, skip=skip, request_options=request_options
        )
        return _response.data

    async def attach_firewall_group(
        self,
        firewall_group_id: str,
        *,
        workspace_id: str,
        vm_id: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FirewallGroup:
        """
        Parameters
        ----------
        firewall_group_id : str
            Firewall group ID.

        workspace_id : str
            The workspace ID to scope this request to.

        vm_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FirewallGroup
            VM attached successfully.

        Examples
        --------
        import asyncio

        from ibee import AsyncIbee

        client = AsyncIbee(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.firewalls.attach_firewall_group(
                firewall_group_id="firewall_group_id",
                workspace_id="workspace_id",
                vm_id="vm_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.attach_firewall_group(
            firewall_group_id, workspace_id=workspace_id, vm_id=vm_id, request_options=request_options
        )
        return _response.data

    async def detach_firewall_group(
        self,
        firewall_group_id: str,
        vm_id: str,
        *,
        workspace_id: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FirewallGroup:
        """
        Parameters
        ----------
        firewall_group_id : str
            Firewall group ID.

        vm_id : str
            Virtual machine ID.

        workspace_id : str
            The workspace ID to scope this request to.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FirewallGroup
            VM detached successfully.

        Examples
        --------
        import asyncio

        from ibee import AsyncIbee

        client = AsyncIbee(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.firewalls.detach_firewall_group(
                firewall_group_id="firewall_group_id",
                vm_id="vm_id",
                workspace_id="workspace_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.detach_firewall_group(
            firewall_group_id, vm_id, workspace_id=workspace_id, request_options=request_options
        )
        return _response.data
