# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .create_secret_identity_request_auth_method import CreateSecretIdentityRequestAuthMethod
    from .create_secret_identity_request_token_policy_mode import CreateSecretIdentityRequestTokenPolicyMode
    from .create_secret_identity_scope_request_access_mode import CreateSecretIdentityScopeRequestAccessMode
    from .update_secret_identity_request_token_policy_mode import UpdateSecretIdentityRequestTokenPolicyMode
    from .update_secret_identity_scope_request_access_mode import UpdateSecretIdentityScopeRequestAccessMode
_dynamic_imports: typing.Dict[str, str] = {
    "CreateSecretIdentityRequestAuthMethod": ".create_secret_identity_request_auth_method",
    "CreateSecretIdentityRequestTokenPolicyMode": ".create_secret_identity_request_token_policy_mode",
    "CreateSecretIdentityScopeRequestAccessMode": ".create_secret_identity_scope_request_access_mode",
    "UpdateSecretIdentityRequestTokenPolicyMode": ".update_secret_identity_request_token_policy_mode",
    "UpdateSecretIdentityScopeRequestAccessMode": ".update_secret_identity_scope_request_access_mode",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "CreateSecretIdentityRequestAuthMethod",
    "CreateSecretIdentityRequestTokenPolicyMode",
    "CreateSecretIdentityScopeRequestAccessMode",
    "UpdateSecretIdentityRequestTokenPolicyMode",
    "UpdateSecretIdentityScopeRequestAccessMode",
]
