# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.cloud_vm import CloudVm
from ..types.operation_accepted import OperationAccepted
from ..types.operation_status import OperationStatus
from ..types.vm_metrics import VmMetrics
from .raw_client import AsyncRawCloudVmsClient, RawCloudVmsClient
from .types.create_cloud_vm_request_os_type import CreateCloudVmRequestOsType

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class CloudVmsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawCloudVmsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawCloudVmsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawCloudVmsClient
        """
        return self._raw_client

    def list_cloud_vms(
        self, *, workspace_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[CloudVm]:
        """
        Returns all cloud VMs in the workspace. Requires scope: vm.read.

        Parameters
        ----------
        workspace_id : str
            The workspace ID to scope this request to.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[CloudVm]
            Cloud VMs returned successfully.

        Examples
        --------
        from ibee import Ibee

        client = Ibee(
            token="YOUR_TOKEN",
        )
        client.cloud_vms.list_cloud_vms(
            workspace_id="workspace_id",
        )
        """
        _response = self._raw_client.list_cloud_vms(workspace_id=workspace_id, request_options=request_options)
        return _response.data

    def create_cloud_vm(
        self,
        *,
        workspace_id: str,
        idempotency_key: str,
        name: str,
        site_id: typing.Optional[str] = OMIT,
        os_distro: str,
        os_type: CreateCloudVmRequestOsType,
        template_id: str,
        cpu: int,
        ram_mb: int,
        plan_id: str,
        disk_gb: typing.Optional[int] = OMIT,
        ssh_key_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        tags: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OperationAccepted:
        """
        Creates a cloud VM. Returns an operation you can poll for status. Requires scope: vm.write.

        Parameters
        ----------
        workspace_id : str
            The workspace ID to scope this request to.

        idempotency_key : str
            Unique key used to safely retry write operations.

        name : str
            Display name for the virtual machine.

        site_id : typing.Optional[str]
            Optional placement site ID. Omit for automatic placement.

        os_distro : str
            Operating system distribution (e.g. ubuntu, centos, debian, rocky, windows).

        os_type : CreateCloudVmRequestOsType
            Operating system family.

        template_id : str
            OS template or image ID returned by the compute catalog.

        cpu : int
            Number of vCPUs.

        ram_mb : int
            RAM in megabytes.

        plan_id : str
            Billable compute plan ID returned by the compute catalog.

        disk_gb : typing.Optional[int]
            Root disk size in gigabytes.

        ssh_key_ids : typing.Optional[typing.Sequence[str]]
            SSH key IDs to inject into the VM.

        tags : typing.Optional[typing.Sequence[str]]
            Arbitrary tags for filtering and organization.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OperationAccepted
            VM creation accepted.

        Examples
        --------
        from ibee import Ibee

        client = Ibee(
            token="YOUR_TOKEN",
        )
        client.cloud_vms.create_cloud_vm(
            idempotency_key="X-Idempotency-Key",
            workspace_id="workspace_id",
            name="web-server-01",
            site_id="site_id",
            os_distro="ubuntu",
            os_type="linux",
            template_id="tmpl_ubuntu_2204",
            cpu=2,
            ram_mb=4096,
            plan_id="plan_id",
        )
        """
        _response = self._raw_client.create_cloud_vm(
            workspace_id=workspace_id,
            idempotency_key=idempotency_key,
            name=name,
            site_id=site_id,
            os_distro=os_distro,
            os_type=os_type,
            template_id=template_id,
            cpu=cpu,
            ram_mb=ram_mb,
            plan_id=plan_id,
            disk_gb=disk_gb,
            ssh_key_ids=ssh_key_ids,
            tags=tags,
            request_options=request_options,
        )
        return _response.data

    def get_cloud_vm(
        self, vm_id: str, *, workspace_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> CloudVm:
        """
        Returns a single cloud VM. Requires scope: vm.read.

        Parameters
        ----------
        vm_id : str
            Virtual machine ID.

        workspace_id : str
            The workspace ID to scope this request to.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CloudVm
            Cloud VM returned successfully.

        Examples
        --------
        from ibee import Ibee

        client = Ibee(
            token="YOUR_TOKEN",
        )
        client.cloud_vms.get_cloud_vm(
            vm_id="vm_id",
            workspace_id="workspace_id",
        )
        """
        _response = self._raw_client.get_cloud_vm(vm_id, workspace_id=workspace_id, request_options=request_options)
        return _response.data

    def delete_cloud_vm(
        self,
        vm_id: str,
        *,
        workspace_id: str,
        idempotency_key: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OperationAccepted:
        """
        Deletes a cloud VM. Returns an operation you can poll for status. Requires scope: vm.write.

        Parameters
        ----------
        vm_id : str
            Virtual machine ID.

        workspace_id : str
            The workspace ID to scope this request to.

        idempotency_key : str
            Unique key used to safely retry write operations.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OperationAccepted
            VM deletion accepted.

        Examples
        --------
        from ibee import Ibee

        client = Ibee(
            token="YOUR_TOKEN",
        )
        client.cloud_vms.delete_cloud_vm(
            vm_id="vm_id",
            idempotency_key="X-Idempotency-Key",
            workspace_id="workspace_id",
        )
        """
        _response = self._raw_client.delete_cloud_vm(
            vm_id, workspace_id=workspace_id, idempotency_key=idempotency_key, request_options=request_options
        )
        return _response.data

    def start_cloud_vm(
        self,
        vm_id: str,
        *,
        workspace_id: str,
        idempotency_key: str,
        force: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OperationAccepted:
        """
        Starts a stopped cloud VM. Requires scope: vm.write.

        Parameters
        ----------
        vm_id : str
            Virtual machine ID.

        workspace_id : str
            The workspace ID to scope this request to.

        idempotency_key : str
            Unique key used to safely retry write operations.

        force : typing.Optional[bool]
            Force the action even if the VM is in a transitional state.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OperationAccepted
            VM start accepted.

        Examples
        --------
        from ibee import Ibee

        client = Ibee(
            token="YOUR_TOKEN",
        )
        client.cloud_vms.start_cloud_vm(
            vm_id="vm_id",
            idempotency_key="X-Idempotency-Key",
            workspace_id="workspace_id",
        )
        """
        _response = self._raw_client.start_cloud_vm(
            vm_id,
            workspace_id=workspace_id,
            idempotency_key=idempotency_key,
            force=force,
            request_options=request_options,
        )
        return _response.data

    def stop_cloud_vm(
        self,
        vm_id: str,
        *,
        workspace_id: str,
        idempotency_key: str,
        force: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OperationAccepted:
        """
        Stops a running cloud VM. Requires scope: vm.write.

        Parameters
        ----------
        vm_id : str
            Virtual machine ID.

        workspace_id : str
            The workspace ID to scope this request to.

        idempotency_key : str
            Unique key used to safely retry write operations.

        force : typing.Optional[bool]
            Force the action even if the VM is in a transitional state.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OperationAccepted
            VM stop accepted.

        Examples
        --------
        from ibee import Ibee

        client = Ibee(
            token="YOUR_TOKEN",
        )
        client.cloud_vms.stop_cloud_vm(
            vm_id="vm_id",
            idempotency_key="X-Idempotency-Key",
            workspace_id="workspace_id",
        )
        """
        _response = self._raw_client.stop_cloud_vm(
            vm_id,
            workspace_id=workspace_id,
            idempotency_key=idempotency_key,
            force=force,
            request_options=request_options,
        )
        return _response.data

    def reboot_cloud_vm(
        self,
        vm_id: str,
        *,
        workspace_id: str,
        idempotency_key: str,
        force: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OperationAccepted:
        """
        Reboots a cloud VM. Requires scope: vm.write.

        Parameters
        ----------
        vm_id : str
            Virtual machine ID.

        workspace_id : str
            The workspace ID to scope this request to.

        idempotency_key : str
            Unique key used to safely retry write operations.

        force : typing.Optional[bool]
            Force the action even if the VM is in a transitional state.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OperationAccepted
            VM reboot accepted.

        Examples
        --------
        from ibee import Ibee

        client = Ibee(
            token="YOUR_TOKEN",
        )
        client.cloud_vms.reboot_cloud_vm(
            vm_id="vm_id",
            idempotency_key="X-Idempotency-Key",
            workspace_id="workspace_id",
        )
        """
        _response = self._raw_client.reboot_cloud_vm(
            vm_id,
            workspace_id=workspace_id,
            idempotency_key=idempotency_key,
            force=force,
            request_options=request_options,
        )
        return _response.data

    def get_cloud_vm_metrics(
        self, vm_id: str, *, workspace_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> VmMetrics:
        """
        Returns current resource-usage metrics for a cloud VM. Requires scope: vm.read.

        Parameters
        ----------
        vm_id : str
            Virtual machine ID.

        workspace_id : str
            The workspace ID to scope this request to.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        VmMetrics
            VM metrics returned successfully.

        Examples
        --------
        from ibee import Ibee

        client = Ibee(
            token="YOUR_TOKEN",
        )
        client.cloud_vms.get_cloud_vm_metrics(
            vm_id="vm_id",
            workspace_id="workspace_id",
        )
        """
        _response = self._raw_client.get_cloud_vm_metrics(
            vm_id, workspace_id=workspace_id, request_options=request_options
        )
        return _response.data

    def get_compute_operation(
        self, operation_id: str, *, workspace_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> OperationStatus:
        """
        Returns the status of an async compute operation (create, delete, start, stop, reboot). Works for both cloud VM and GPU VM operations. Requires scope: vm.read.

        Parameters
        ----------
        operation_id : str
            Operation ID returned by a create, delete, or power-action request.

        workspace_id : str
            The workspace ID to scope this request to.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OperationStatus
            Operation returned successfully.

        Examples
        --------
        from ibee import Ibee

        client = Ibee(
            token="YOUR_TOKEN",
        )
        client.cloud_vms.get_compute_operation(
            operation_id="operation_id",
            workspace_id="workspace_id",
        )
        """
        _response = self._raw_client.get_compute_operation(
            operation_id, workspace_id=workspace_id, request_options=request_options
        )
        return _response.data


class AsyncCloudVmsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawCloudVmsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawCloudVmsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawCloudVmsClient
        """
        return self._raw_client

    async def list_cloud_vms(
        self, *, workspace_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[CloudVm]:
        """
        Returns all cloud VMs in the workspace. Requires scope: vm.read.

        Parameters
        ----------
        workspace_id : str
            The workspace ID to scope this request to.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[CloudVm]
            Cloud VMs returned successfully.

        Examples
        --------
        import asyncio

        from ibee import AsyncIbee

        client = AsyncIbee(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.cloud_vms.list_cloud_vms(
                workspace_id="workspace_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_cloud_vms(workspace_id=workspace_id, request_options=request_options)
        return _response.data

    async def create_cloud_vm(
        self,
        *,
        workspace_id: str,
        idempotency_key: str,
        name: str,
        site_id: typing.Optional[str] = OMIT,
        os_distro: str,
        os_type: CreateCloudVmRequestOsType,
        template_id: str,
        cpu: int,
        ram_mb: int,
        plan_id: str,
        disk_gb: typing.Optional[int] = OMIT,
        ssh_key_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        tags: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OperationAccepted:
        """
        Creates a cloud VM. Returns an operation you can poll for status. Requires scope: vm.write.

        Parameters
        ----------
        workspace_id : str
            The workspace ID to scope this request to.

        idempotency_key : str
            Unique key used to safely retry write operations.

        name : str
            Display name for the virtual machine.

        site_id : typing.Optional[str]
            Optional placement site ID. Omit for automatic placement.

        os_distro : str
            Operating system distribution (e.g. ubuntu, centos, debian, rocky, windows).

        os_type : CreateCloudVmRequestOsType
            Operating system family.

        template_id : str
            OS template or image ID returned by the compute catalog.

        cpu : int
            Number of vCPUs.

        ram_mb : int
            RAM in megabytes.

        plan_id : str
            Billable compute plan ID returned by the compute catalog.

        disk_gb : typing.Optional[int]
            Root disk size in gigabytes.

        ssh_key_ids : typing.Optional[typing.Sequence[str]]
            SSH key IDs to inject into the VM.

        tags : typing.Optional[typing.Sequence[str]]
            Arbitrary tags for filtering and organization.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OperationAccepted
            VM creation accepted.

        Examples
        --------
        import asyncio

        from ibee import AsyncIbee

        client = AsyncIbee(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.cloud_vms.create_cloud_vm(
                idempotency_key="X-Idempotency-Key",
                workspace_id="workspace_id",
                name="web-server-01",
                site_id="site_id",
                os_distro="ubuntu",
                os_type="linux",
                template_id="tmpl_ubuntu_2204",
                cpu=2,
                ram_mb=4096,
                plan_id="plan_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_cloud_vm(
            workspace_id=workspace_id,
            idempotency_key=idempotency_key,
            name=name,
            site_id=site_id,
            os_distro=os_distro,
            os_type=os_type,
            template_id=template_id,
            cpu=cpu,
            ram_mb=ram_mb,
            plan_id=plan_id,
            disk_gb=disk_gb,
            ssh_key_ids=ssh_key_ids,
            tags=tags,
            request_options=request_options,
        )
        return _response.data

    async def get_cloud_vm(
        self, vm_id: str, *, workspace_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> CloudVm:
        """
        Returns a single cloud VM. Requires scope: vm.read.

        Parameters
        ----------
        vm_id : str
            Virtual machine ID.

        workspace_id : str
            The workspace ID to scope this request to.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CloudVm
            Cloud VM returned successfully.

        Examples
        --------
        import asyncio

        from ibee import AsyncIbee

        client = AsyncIbee(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.cloud_vms.get_cloud_vm(
                vm_id="vm_id",
                workspace_id="workspace_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_cloud_vm(
            vm_id, workspace_id=workspace_id, request_options=request_options
        )
        return _response.data

    async def delete_cloud_vm(
        self,
        vm_id: str,
        *,
        workspace_id: str,
        idempotency_key: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OperationAccepted:
        """
        Deletes a cloud VM. Returns an operation you can poll for status. Requires scope: vm.write.

        Parameters
        ----------
        vm_id : str
            Virtual machine ID.

        workspace_id : str
            The workspace ID to scope this request to.

        idempotency_key : str
            Unique key used to safely retry write operations.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OperationAccepted
            VM deletion accepted.

        Examples
        --------
        import asyncio

        from ibee import AsyncIbee

        client = AsyncIbee(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.cloud_vms.delete_cloud_vm(
                vm_id="vm_id",
                idempotency_key="X-Idempotency-Key",
                workspace_id="workspace_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_cloud_vm(
            vm_id, workspace_id=workspace_id, idempotency_key=idempotency_key, request_options=request_options
        )
        return _response.data

    async def start_cloud_vm(
        self,
        vm_id: str,
        *,
        workspace_id: str,
        idempotency_key: str,
        force: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OperationAccepted:
        """
        Starts a stopped cloud VM. Requires scope: vm.write.

        Parameters
        ----------
        vm_id : str
            Virtual machine ID.

        workspace_id : str
            The workspace ID to scope this request to.

        idempotency_key : str
            Unique key used to safely retry write operations.

        force : typing.Optional[bool]
            Force the action even if the VM is in a transitional state.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OperationAccepted
            VM start accepted.

        Examples
        --------
        import asyncio

        from ibee import AsyncIbee

        client = AsyncIbee(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.cloud_vms.start_cloud_vm(
                vm_id="vm_id",
                idempotency_key="X-Idempotency-Key",
                workspace_id="workspace_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.start_cloud_vm(
            vm_id,
            workspace_id=workspace_id,
            idempotency_key=idempotency_key,
            force=force,
            request_options=request_options,
        )
        return _response.data

    async def stop_cloud_vm(
        self,
        vm_id: str,
        *,
        workspace_id: str,
        idempotency_key: str,
        force: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OperationAccepted:
        """
        Stops a running cloud VM. Requires scope: vm.write.

        Parameters
        ----------
        vm_id : str
            Virtual machine ID.

        workspace_id : str
            The workspace ID to scope this request to.

        idempotency_key : str
            Unique key used to safely retry write operations.

        force : typing.Optional[bool]
            Force the action even if the VM is in a transitional state.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OperationAccepted
            VM stop accepted.

        Examples
        --------
        import asyncio

        from ibee import AsyncIbee

        client = AsyncIbee(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.cloud_vms.stop_cloud_vm(
                vm_id="vm_id",
                idempotency_key="X-Idempotency-Key",
                workspace_id="workspace_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.stop_cloud_vm(
            vm_id,
            workspace_id=workspace_id,
            idempotency_key=idempotency_key,
            force=force,
            request_options=request_options,
        )
        return _response.data

    async def reboot_cloud_vm(
        self,
        vm_id: str,
        *,
        workspace_id: str,
        idempotency_key: str,
        force: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OperationAccepted:
        """
        Reboots a cloud VM. Requires scope: vm.write.

        Parameters
        ----------
        vm_id : str
            Virtual machine ID.

        workspace_id : str
            The workspace ID to scope this request to.

        idempotency_key : str
            Unique key used to safely retry write operations.

        force : typing.Optional[bool]
            Force the action even if the VM is in a transitional state.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OperationAccepted
            VM reboot accepted.

        Examples
        --------
        import asyncio

        from ibee import AsyncIbee

        client = AsyncIbee(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.cloud_vms.reboot_cloud_vm(
                vm_id="vm_id",
                idempotency_key="X-Idempotency-Key",
                workspace_id="workspace_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.reboot_cloud_vm(
            vm_id,
            workspace_id=workspace_id,
            idempotency_key=idempotency_key,
            force=force,
            request_options=request_options,
        )
        return _response.data

    async def get_cloud_vm_metrics(
        self, vm_id: str, *, workspace_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> VmMetrics:
        """
        Returns current resource-usage metrics for a cloud VM. Requires scope: vm.read.

        Parameters
        ----------
        vm_id : str
            Virtual machine ID.

        workspace_id : str
            The workspace ID to scope this request to.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        VmMetrics
            VM metrics returned successfully.

        Examples
        --------
        import asyncio

        from ibee import AsyncIbee

        client = AsyncIbee(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.cloud_vms.get_cloud_vm_metrics(
                vm_id="vm_id",
                workspace_id="workspace_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_cloud_vm_metrics(
            vm_id, workspace_id=workspace_id, request_options=request_options
        )
        return _response.data

    async def get_compute_operation(
        self, operation_id: str, *, workspace_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> OperationStatus:
        """
        Returns the status of an async compute operation (create, delete, start, stop, reboot). Works for both cloud VM and GPU VM operations. Requires scope: vm.read.

        Parameters
        ----------
        operation_id : str
            Operation ID returned by a create, delete, or power-action request.

        workspace_id : str
            The workspace ID to scope this request to.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OperationStatus
            Operation returned successfully.

        Examples
        --------
        import asyncio

        from ibee import AsyncIbee

        client = AsyncIbee(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.cloud_vms.get_compute_operation(
                operation_id="operation_id",
                workspace_id="workspace_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_compute_operation(
            operation_id, workspace_id=workspace_id, request_options=request_options
        )
        return _response.data
