# Originally generated by Fern; hand-modified for IBEE 0.4.0 (listed in .fernignore).
#
# ApiError now extracts a stable, lower-case ``code`` and a human ``message`` from
# every error body shape the public API returns (edge authorizer, FastAPI
# ``detail`` string/object/list, secret-store ``{"error": {...}}``, plain text).

from __future__ import annotations

import typing
from typing import Any, Dict, Optional

STATUS_DEFAULT_CODES: Dict[int, str] = {
    400: "bad_request",
    401: "unauthorized",
    402: "payment_required",
    403: "forbidden",
    404: "not_found",
    409: "conflict",
    413: "request_body_too_large",
    422: "validation_error",
    423: "locked",
    429: "rate_limited",
    500: "internal_error",
    502: "bad_gateway",
    503: "service_unavailable",
    504: "gateway_timeout",
}
RETRYABLE_STATUS_CODES = frozenset({429, 502, 503, 504})


def _to_plain(body: Any) -> Any:
    """Convert a pydantic model (for example the generated ``Error``) to plain data."""
    if body is None or isinstance(body, (str, bytes, int, float, bool, list, dict)):
        return body
    dump = getattr(body, "model_dump", None)
    if callable(dump):
        try:
            return dump(mode="json")
        except Exception:  # pragma: no cover - defensive
            pass
    legacy = getattr(body, "dict", None)
    if callable(legacy):
        try:
            return legacy()
        except Exception:  # pragma: no cover - defensive
            pass
    return body


def _text(value: Any) -> Optional[str]:
    if value is None:
        return None
    text = str(value).strip()
    return text or None


def _format_validation_list(items: typing.Sequence[Any]) -> str:
    messages = []
    for item in items:
        if isinstance(item, dict):
            loc = item.get("loc")
            msg = _text(item.get("msg")) or _text(item.get("message")) or "invalid value"
            field = loc[-1] if isinstance(loc, (list, tuple)) and loc else None
            messages.append(f"{field}: {msg}" if field is not None else msg)
        else:
            text = _text(item)
            if text:
                messages.append(text)
    return ", ".join(messages)


def _header(headers: Optional[typing.Mapping[str, Any]], name: str) -> Optional[str]:
    if not headers:
        return None
    for key, value in headers.items():
        if isinstance(key, str) and key.lower() == name:
            return None if value is None else str(value)
    return None


def parse_error_payload(
    status_code: Optional[int], body: Any, headers: Optional[typing.Mapping[str, Any]] = None
) -> Dict[str, Any]:
    """Extract ``code``, ``raw_code``, ``reason``, ``message`` and related fields from an error body.

    The first matching shape wins:

    1. ``{"error": "<code>", ...}`` from the API edge (also reads ``billing_reason``,
       ``required_scope``, ``billing_sku_code`` and ``admission_context_id``);
    2. ``{"error": {"code", "message", "details"}}``;
    3. ``{"detail": {...}}``;
    4. ``{"detail": [...]}`` (field validation errors, formatted ``field: message``);
    5. ``{"detail": "..."}``;
    6. top-level ``code``/``reason``/``message``;
    7. a plain-text body.
    """
    plain = _to_plain(body)
    info: Dict[str, Any] = {
        "raw_code": None,
        "reason": None,
        "message": None,
        "details": None,
        "required_scope": None,
        "billing_sku_code": None,
        "admission_context_id": None,
    }
    if isinstance(plain, dict):
        error = plain.get("error")
        detail = plain.get("detail")
        if isinstance(error, str):
            info["raw_code"] = error
            info["reason"] = _text(plain.get("billing_reason"))
            info["required_scope"] = _text(plain.get("required_scope"))
            info["billing_sku_code"] = _text(plain.get("billing_sku_code"))
            info["admission_context_id"] = _text(plain.get("admission_context_id"))
            info["message"] = _text(plain.get("message"))
        elif isinstance(error, dict):
            info["raw_code"] = _text(error.get("code"))
            info["message"] = _text(error.get("message"))
            info["details"] = error.get("details")
        elif isinstance(detail, dict):
            info["raw_code"] = _text(detail.get("code")) or _text(detail.get("error_code")) or _text(detail.get("error"))
            info["message"] = _text(detail.get("message"))
            info["reason"] = _text(detail.get("reason"))
            info["details"] = detail
            info["required_scope"] = _text(detail.get("required_scope"))
        elif isinstance(detail, list):
            info["raw_code"] = "validation_error"
            info["message"] = _format_validation_list(detail) or None
            info["details"] = detail
        elif isinstance(detail, str):
            info["message"] = _text(detail)
        else:
            info["raw_code"] = _text(plain.get("code"))
            info["reason"] = _text(plain.get("reason"))
            info["message"] = _text(plain.get("message"))
        if info["admission_context_id"] is None:
            info["admission_context_id"] = _text(plain.get("admission_context_id"))
    elif isinstance(plain, (str, bytes)):
        text = plain.decode("utf-8", "replace") if isinstance(plain, bytes) else plain
        info["message"] = _text(text)
    raw_code = info["raw_code"]
    if raw_code:
        code = raw_code.strip().lower()
    elif status_code is not None:
        code = STATUS_DEFAULT_CODES.get(status_code, f"http_{status_code}")
    else:
        code = "api_error"
    info["code"] = code
    if not info["message"]:
        info["message"] = f"IBEE API error {status_code}" if status_code is not None else "IBEE API error"
    info["request_id"] = _header(headers, "x-request-id")
    from ..retry import parse_retry_after

    info["retry_after"] = parse_retry_after(dict(headers)) if headers else None
    return info


class ApiError(Exception):
    """An error HTTP response from the IBEE API.

    Attributes
    ----------
    status_code, headers, body
        As in 0.3.0. ``body`` is the typed ``Error`` model for JSON object bodies on
        400/401/402/403/404/409/502/503, and the raw body otherwise.
    raw_body
        The parsed JSON (or text) body exactly as received.
    code
        Stable lower-case code (for example ``insufficient_scope``, ``not_found``).
    raw_code
        The code exactly as the server sent it, when it sent one.
    reason
        Decision reason (for example the billing reason on a 402).
    message
        Human-readable message.
    required_scope, billing_sku_code, admission_context_id
        Fields the API edge adds to authorization and billing denials.
    request_id
        The ``x-request-id`` response header, when present.
    retry_after
        Seconds from ``Retry-After``, when present.
    details
        Structured error details, when present.
    idempotency_key
        The idempotency key sent with the failed request, when there was one.
    retryable
        ``True`` for 429/502/503/504.
    """

    headers: Optional[Dict[str, str]]
    status_code: Optional[int]
    body: Any

    def __init__(
        self,
        *,
        headers: Optional[Dict[str, str]] = None,
        status_code: Optional[int] = None,
        body: Any = None,
    ) -> None:
        self.headers = headers
        self.status_code = status_code
        self.body = body
        self.idempotency_key: Optional[str] = None
        self._populate(body)

    def _populate(self, raw_body: Any) -> None:
        info = parse_error_payload(self.status_code, raw_body, self.headers)
        self.raw_body = _to_plain(raw_body)
        self.code: str = info["code"]
        self.raw_code: Optional[str] = info["raw_code"]
        self.reason: Optional[str] = info["reason"]
        self.message: str = info["message"]
        self.details: Any = info["details"]
        self.required_scope: Optional[str] = info["required_scope"]
        self.billing_sku_code: Optional[str] = info["billing_sku_code"]
        self.admission_context_id: Optional[str] = info["admission_context_id"]
        self.request_id: Optional[str] = info["request_id"]
        self.retry_after: Optional[float] = info["retry_after"]

    @property
    def retryable(self) -> bool:
        return self.status_code in RETRYABLE_STATUS_CODES

    def __str__(self) -> str:
        return f"headers: {self.headers}, status_code: {self.status_code}, body: {self.body}"
