# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.gpu_vm import GpuVm
from ..types.operation_accepted import OperationAccepted
from ..types.vm_metrics import VmMetrics
from .raw_client import AsyncRawGpuVmsClient, RawGpuVmsClient
from .types.create_gpu_vm_request_os_type import CreateGpuVmRequestOsType

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class GpuVmsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawGpuVmsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawGpuVmsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawGpuVmsClient
        """
        return self._raw_client

    def list_gpu_vms(
        self, *, workspace_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[GpuVm]:
        """
        Returns all GPU VMs in the workspace. Requires scope: vm.read.

        Parameters
        ----------
        workspace_id : str
            The workspace ID to scope this request to.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[GpuVm]
            GPU VMs returned successfully.

        Examples
        --------
        from ibee import Ibee

        client = Ibee(
            token="YOUR_TOKEN",
        )
        client.gpu_vms.list_gpu_vms(
            workspace_id="workspace_id",
        )
        """
        _response = self._raw_client.list_gpu_vms(workspace_id=workspace_id, request_options=request_options)
        return _response.data

    def create_gpu_vm(
        self,
        *,
        workspace_id: str,
        idempotency_key: str,
        name: str,
        site_id: typing.Optional[str] = OMIT,
        os_distro: str,
        os_type: CreateGpuVmRequestOsType,
        template_id: str,
        cpu: int,
        ram_mb: int,
        gpu_count: int,
        gpu_model: str,
        plan_id: str,
        disk_gb: typing.Optional[int] = OMIT,
        ssh_key_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        tags: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OperationAccepted:
        """
        Creates a GPU VM. Returns an operation you can poll for status. Requires scope: vm.write.

        Parameters
        ----------
        workspace_id : str
            The workspace ID to scope this request to.

        idempotency_key : str
            Unique key used to safely retry write operations.

        name : str
            Display name for the virtual machine.

        site_id : typing.Optional[str]
            Optional placement site ID. Omit for automatic placement.

        os_distro : str
            Operating system distribution (e.g. ubuntu, centos, debian, rocky).

        os_type : CreateGpuVmRequestOsType
            Operating system family.

        template_id : str
            GPU-compatible template ID returned by the compute catalog.

        cpu : int
            Number of vCPUs.

        ram_mb : int
            RAM in megabytes.

        gpu_count : int
            Number of GPUs to attach.

        gpu_model : str
            GPU model (e.g. A100, H100, L40S, RTX4090).

        plan_id : str
            Billable GPU plan ID returned by the compute catalog.

        disk_gb : typing.Optional[int]
            Root disk size in gigabytes.

        ssh_key_ids : typing.Optional[typing.Sequence[str]]
            SSH key IDs to inject into the VM.

        tags : typing.Optional[typing.Sequence[str]]
            Arbitrary tags for filtering and organization.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OperationAccepted
            VM creation accepted.

        Examples
        --------
        from ibee import Ibee

        client = Ibee(
            token="YOUR_TOKEN",
        )
        client.gpu_vms.create_gpu_vm(
            idempotency_key="X-Idempotency-Key",
            workspace_id="workspace_id",
            name="ml-training-01",
            site_id="site_id",
            os_distro="ubuntu",
            os_type="linux",
            template_id="tmpl_ubuntu_2204_cuda",
            cpu=8,
            ram_mb=32768,
            gpu_count=1,
            gpu_model="A100",
            plan_id="plan_id",
        )
        """
        _response = self._raw_client.create_gpu_vm(
            workspace_id=workspace_id,
            idempotency_key=idempotency_key,
            name=name,
            site_id=site_id,
            os_distro=os_distro,
            os_type=os_type,
            template_id=template_id,
            cpu=cpu,
            ram_mb=ram_mb,
            gpu_count=gpu_count,
            gpu_model=gpu_model,
            plan_id=plan_id,
            disk_gb=disk_gb,
            ssh_key_ids=ssh_key_ids,
            tags=tags,
            request_options=request_options,
        )
        return _response.data

    def get_gpu_vm(
        self, vm_id: str, *, workspace_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> GpuVm:
        """
        Returns a single GPU VM. Requires scope: vm.read.

        Parameters
        ----------
        vm_id : str
            Virtual machine ID.

        workspace_id : str
            The workspace ID to scope this request to.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GpuVm
            GPU VM returned successfully.

        Examples
        --------
        from ibee import Ibee

        client = Ibee(
            token="YOUR_TOKEN",
        )
        client.gpu_vms.get_gpu_vm(
            vm_id="vm_id",
            workspace_id="workspace_id",
        )
        """
        _response = self._raw_client.get_gpu_vm(vm_id, workspace_id=workspace_id, request_options=request_options)
        return _response.data

    def delete_gpu_vm(
        self,
        vm_id: str,
        *,
        workspace_id: str,
        idempotency_key: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OperationAccepted:
        """
        Deletes a GPU VM. Returns an operation you can poll for status. Requires scope: vm.write.

        Parameters
        ----------
        vm_id : str
            Virtual machine ID.

        workspace_id : str
            The workspace ID to scope this request to.

        idempotency_key : str
            Unique key used to safely retry write operations.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OperationAccepted
            VM deletion accepted.

        Examples
        --------
        from ibee import Ibee

        client = Ibee(
            token="YOUR_TOKEN",
        )
        client.gpu_vms.delete_gpu_vm(
            vm_id="vm_id",
            idempotency_key="X-Idempotency-Key",
            workspace_id="workspace_id",
        )
        """
        _response = self._raw_client.delete_gpu_vm(
            vm_id, workspace_id=workspace_id, idempotency_key=idempotency_key, request_options=request_options
        )
        return _response.data

    def start_gpu_vm(
        self,
        vm_id: str,
        *,
        workspace_id: str,
        idempotency_key: str,
        force: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OperationAccepted:
        """
        Starts a stopped GPU VM. Requires scope: vm.write.

        Parameters
        ----------
        vm_id : str
            Virtual machine ID.

        workspace_id : str
            The workspace ID to scope this request to.

        idempotency_key : str
            Unique key used to safely retry write operations.

        force : typing.Optional[bool]
            Force the action even if the VM is in a transitional state.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OperationAccepted
            VM start accepted.

        Examples
        --------
        from ibee import Ibee

        client = Ibee(
            token="YOUR_TOKEN",
        )
        client.gpu_vms.start_gpu_vm(
            vm_id="vm_id",
            idempotency_key="X-Idempotency-Key",
            workspace_id="workspace_id",
        )
        """
        _response = self._raw_client.start_gpu_vm(
            vm_id,
            workspace_id=workspace_id,
            idempotency_key=idempotency_key,
            force=force,
            request_options=request_options,
        )
        return _response.data

    def stop_gpu_vm(
        self,
        vm_id: str,
        *,
        workspace_id: str,
        idempotency_key: str,
        force: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OperationAccepted:
        """
        Stops a running GPU VM. Requires scope: vm.write.

        Parameters
        ----------
        vm_id : str
            Virtual machine ID.

        workspace_id : str
            The workspace ID to scope this request to.

        idempotency_key : str
            Unique key used to safely retry write operations.

        force : typing.Optional[bool]
            Force the action even if the VM is in a transitional state.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OperationAccepted
            VM stop accepted.

        Examples
        --------
        from ibee import Ibee

        client = Ibee(
            token="YOUR_TOKEN",
        )
        client.gpu_vms.stop_gpu_vm(
            vm_id="vm_id",
            idempotency_key="X-Idempotency-Key",
            workspace_id="workspace_id",
        )
        """
        _response = self._raw_client.stop_gpu_vm(
            vm_id,
            workspace_id=workspace_id,
            idempotency_key=idempotency_key,
            force=force,
            request_options=request_options,
        )
        return _response.data

    def reboot_gpu_vm(
        self,
        vm_id: str,
        *,
        workspace_id: str,
        idempotency_key: str,
        force: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OperationAccepted:
        """
        Reboots a GPU VM. Requires scope: vm.write.

        Parameters
        ----------
        vm_id : str
            Virtual machine ID.

        workspace_id : str
            The workspace ID to scope this request to.

        idempotency_key : str
            Unique key used to safely retry write operations.

        force : typing.Optional[bool]
            Force the action even if the VM is in a transitional state.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OperationAccepted
            VM reboot accepted.

        Examples
        --------
        from ibee import Ibee

        client = Ibee(
            token="YOUR_TOKEN",
        )
        client.gpu_vms.reboot_gpu_vm(
            vm_id="vm_id",
            idempotency_key="X-Idempotency-Key",
            workspace_id="workspace_id",
        )
        """
        _response = self._raw_client.reboot_gpu_vm(
            vm_id,
            workspace_id=workspace_id,
            idempotency_key=idempotency_key,
            force=force,
            request_options=request_options,
        )
        return _response.data

    def get_gpu_vm_metrics(
        self, vm_id: str, *, workspace_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> VmMetrics:
        """
        Returns current resource-usage metrics for a GPU VM. Requires scope: vm.read.

        Parameters
        ----------
        vm_id : str
            Virtual machine ID.

        workspace_id : str
            The workspace ID to scope this request to.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        VmMetrics
            VM metrics returned successfully.

        Examples
        --------
        from ibee import Ibee

        client = Ibee(
            token="YOUR_TOKEN",
        )
        client.gpu_vms.get_gpu_vm_metrics(
            vm_id="vm_id",
            workspace_id="workspace_id",
        )
        """
        _response = self._raw_client.get_gpu_vm_metrics(
            vm_id, workspace_id=workspace_id, request_options=request_options
        )
        return _response.data


class AsyncGpuVmsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawGpuVmsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawGpuVmsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawGpuVmsClient
        """
        return self._raw_client

    async def list_gpu_vms(
        self, *, workspace_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[GpuVm]:
        """
        Returns all GPU VMs in the workspace. Requires scope: vm.read.

        Parameters
        ----------
        workspace_id : str
            The workspace ID to scope this request to.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[GpuVm]
            GPU VMs returned successfully.

        Examples
        --------
        import asyncio

        from ibee import AsyncIbee

        client = AsyncIbee(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.gpu_vms.list_gpu_vms(
                workspace_id="workspace_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_gpu_vms(workspace_id=workspace_id, request_options=request_options)
        return _response.data

    async def create_gpu_vm(
        self,
        *,
        workspace_id: str,
        idempotency_key: str,
        name: str,
        site_id: typing.Optional[str] = OMIT,
        os_distro: str,
        os_type: CreateGpuVmRequestOsType,
        template_id: str,
        cpu: int,
        ram_mb: int,
        gpu_count: int,
        gpu_model: str,
        plan_id: str,
        disk_gb: typing.Optional[int] = OMIT,
        ssh_key_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        tags: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OperationAccepted:
        """
        Creates a GPU VM. Returns an operation you can poll for status. Requires scope: vm.write.

        Parameters
        ----------
        workspace_id : str
            The workspace ID to scope this request to.

        idempotency_key : str
            Unique key used to safely retry write operations.

        name : str
            Display name for the virtual machine.

        site_id : typing.Optional[str]
            Optional placement site ID. Omit for automatic placement.

        os_distro : str
            Operating system distribution (e.g. ubuntu, centos, debian, rocky).

        os_type : CreateGpuVmRequestOsType
            Operating system family.

        template_id : str
            GPU-compatible template ID returned by the compute catalog.

        cpu : int
            Number of vCPUs.

        ram_mb : int
            RAM in megabytes.

        gpu_count : int
            Number of GPUs to attach.

        gpu_model : str
            GPU model (e.g. A100, H100, L40S, RTX4090).

        plan_id : str
            Billable GPU plan ID returned by the compute catalog.

        disk_gb : typing.Optional[int]
            Root disk size in gigabytes.

        ssh_key_ids : typing.Optional[typing.Sequence[str]]
            SSH key IDs to inject into the VM.

        tags : typing.Optional[typing.Sequence[str]]
            Arbitrary tags for filtering and organization.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OperationAccepted
            VM creation accepted.

        Examples
        --------
        import asyncio

        from ibee import AsyncIbee

        client = AsyncIbee(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.gpu_vms.create_gpu_vm(
                idempotency_key="X-Idempotency-Key",
                workspace_id="workspace_id",
                name="ml-training-01",
                site_id="site_id",
                os_distro="ubuntu",
                os_type="linux",
                template_id="tmpl_ubuntu_2204_cuda",
                cpu=8,
                ram_mb=32768,
                gpu_count=1,
                gpu_model="A100",
                plan_id="plan_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_gpu_vm(
            workspace_id=workspace_id,
            idempotency_key=idempotency_key,
            name=name,
            site_id=site_id,
            os_distro=os_distro,
            os_type=os_type,
            template_id=template_id,
            cpu=cpu,
            ram_mb=ram_mb,
            gpu_count=gpu_count,
            gpu_model=gpu_model,
            plan_id=plan_id,
            disk_gb=disk_gb,
            ssh_key_ids=ssh_key_ids,
            tags=tags,
            request_options=request_options,
        )
        return _response.data

    async def get_gpu_vm(
        self, vm_id: str, *, workspace_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> GpuVm:
        """
        Returns a single GPU VM. Requires scope: vm.read.

        Parameters
        ----------
        vm_id : str
            Virtual machine ID.

        workspace_id : str
            The workspace ID to scope this request to.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GpuVm
            GPU VM returned successfully.

        Examples
        --------
        import asyncio

        from ibee import AsyncIbee

        client = AsyncIbee(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.gpu_vms.get_gpu_vm(
                vm_id="vm_id",
                workspace_id="workspace_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_gpu_vm(vm_id, workspace_id=workspace_id, request_options=request_options)
        return _response.data

    async def delete_gpu_vm(
        self,
        vm_id: str,
        *,
        workspace_id: str,
        idempotency_key: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OperationAccepted:
        """
        Deletes a GPU VM. Returns an operation you can poll for status. Requires scope: vm.write.

        Parameters
        ----------
        vm_id : str
            Virtual machine ID.

        workspace_id : str
            The workspace ID to scope this request to.

        idempotency_key : str
            Unique key used to safely retry write operations.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OperationAccepted
            VM deletion accepted.

        Examples
        --------
        import asyncio

        from ibee import AsyncIbee

        client = AsyncIbee(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.gpu_vms.delete_gpu_vm(
                vm_id="vm_id",
                idempotency_key="X-Idempotency-Key",
                workspace_id="workspace_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_gpu_vm(
            vm_id, workspace_id=workspace_id, idempotency_key=idempotency_key, request_options=request_options
        )
        return _response.data

    async def start_gpu_vm(
        self,
        vm_id: str,
        *,
        workspace_id: str,
        idempotency_key: str,
        force: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OperationAccepted:
        """
        Starts a stopped GPU VM. Requires scope: vm.write.

        Parameters
        ----------
        vm_id : str
            Virtual machine ID.

        workspace_id : str
            The workspace ID to scope this request to.

        idempotency_key : str
            Unique key used to safely retry write operations.

        force : typing.Optional[bool]
            Force the action even if the VM is in a transitional state.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OperationAccepted
            VM start accepted.

        Examples
        --------
        import asyncio

        from ibee import AsyncIbee

        client = AsyncIbee(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.gpu_vms.start_gpu_vm(
                vm_id="vm_id",
                idempotency_key="X-Idempotency-Key",
                workspace_id="workspace_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.start_gpu_vm(
            vm_id,
            workspace_id=workspace_id,
            idempotency_key=idempotency_key,
            force=force,
            request_options=request_options,
        )
        return _response.data

    async def stop_gpu_vm(
        self,
        vm_id: str,
        *,
        workspace_id: str,
        idempotency_key: str,
        force: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OperationAccepted:
        """
        Stops a running GPU VM. Requires scope: vm.write.

        Parameters
        ----------
        vm_id : str
            Virtual machine ID.

        workspace_id : str
            The workspace ID to scope this request to.

        idempotency_key : str
            Unique key used to safely retry write operations.

        force : typing.Optional[bool]
            Force the action even if the VM is in a transitional state.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OperationAccepted
            VM stop accepted.

        Examples
        --------
        import asyncio

        from ibee import AsyncIbee

        client = AsyncIbee(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.gpu_vms.stop_gpu_vm(
                vm_id="vm_id",
                idempotency_key="X-Idempotency-Key",
                workspace_id="workspace_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.stop_gpu_vm(
            vm_id,
            workspace_id=workspace_id,
            idempotency_key=idempotency_key,
            force=force,
            request_options=request_options,
        )
        return _response.data

    async def reboot_gpu_vm(
        self,
        vm_id: str,
        *,
        workspace_id: str,
        idempotency_key: str,
        force: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OperationAccepted:
        """
        Reboots a GPU VM. Requires scope: vm.write.

        Parameters
        ----------
        vm_id : str
            Virtual machine ID.

        workspace_id : str
            The workspace ID to scope this request to.

        idempotency_key : str
            Unique key used to safely retry write operations.

        force : typing.Optional[bool]
            Force the action even if the VM is in a transitional state.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OperationAccepted
            VM reboot accepted.

        Examples
        --------
        import asyncio

        from ibee import AsyncIbee

        client = AsyncIbee(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.gpu_vms.reboot_gpu_vm(
                vm_id="vm_id",
                idempotency_key="X-Idempotency-Key",
                workspace_id="workspace_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.reboot_gpu_vm(
            vm_id,
            workspace_id=workspace_id,
            idempotency_key=idempotency_key,
            force=force,
            request_options=request_options,
        )
        return _response.data

    async def get_gpu_vm_metrics(
        self, vm_id: str, *, workspace_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> VmMetrics:
        """
        Returns current resource-usage metrics for a GPU VM. Requires scope: vm.read.

        Parameters
        ----------
        vm_id : str
            Virtual machine ID.

        workspace_id : str
            The workspace ID to scope this request to.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        VmMetrics
            VM metrics returned successfully.

        Examples
        --------
        import asyncio

        from ibee import AsyncIbee

        client = AsyncIbee(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.gpu_vms.get_gpu_vm_metrics(
                vm_id="vm_id",
                workspace_id="workspace_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_gpu_vm_metrics(
            vm_id, workspace_id=workspace_id, request_options=request_options
        )
        return _response.data
