# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import encode_path_param
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..errors.bad_request_error import BadRequestError
from ..errors.conflict_error import ConflictError
from ..errors.forbidden_error import ForbiddenError
from ..errors.not_found_error import NotFoundError
from ..errors.unauthorized_error import UnauthorizedError
from ..types.delete_response import DeleteResponse
from ..types.error import Error
from ..types.gpu_vm import GpuVm
from ..types.network_interface import NetworkInterface
from ..types.operation_accepted import OperationAccepted
from ..types.vm_metrics import VmMetrics
from .types.create_gpu_vm_request_os_type import CreateGpuVmRequestOsType
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawGpuVmsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list_gpu_vms(
        self, *, workspace_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[typing.List[GpuVm]]:
        """
        Returns all GPU VMs in the workspace. Requires scope: vm.read.

        Parameters
        ----------
        workspace_id : str
            The workspace ID to scope this request to.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[typing.List[GpuVm]]
            GPU VMs returned successfully.
        """
        _response = self._client_wrapper.httpx_client.request(
            "compute/gpu-vms/",
            method="GET",
            params={
                "workspace_id": workspace_id,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.List[GpuVm],
                    parse_obj_as(
                        type_=typing.List[GpuVm],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def create_gpu_vm(
        self,
        *,
        workspace_id: str,
        idempotency_key: str,
        name: str,
        os_distro: str,
        os_type: CreateGpuVmRequestOsType,
        cpu: int,
        ram_mb: int,
        gpu_count: int,
        gpu_model: str,
        template_id: typing.Optional[str] = OMIT,
        disk_gb: typing.Optional[int] = OMIT,
        plan_id: typing.Optional[str] = OMIT,
        ssh_key_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        tags: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[OperationAccepted]:
        """
        Creates a GPU VM. Returns an operation you can poll for status. Requires scope: vm.write.

        Parameters
        ----------
        workspace_id : str
            The workspace ID to scope this request to.

        idempotency_key : str
            Unique key used to safely retry write operations.

        name : str
            Display name for the virtual machine.

        os_distro : str
            Operating system distribution (e.g. ubuntu, centos, debian, rocky).

        os_type : CreateGpuVmRequestOsType
            Operating system family.

        cpu : int
            Number of vCPUs.

        ram_mb : int
            RAM in megabytes.

        gpu_count : int
            Number of GPUs to attach.

        gpu_model : str
            GPU model (e.g. A100, H100, L40S, RTX4090).

        template_id : typing.Optional[str]
            OS template or image ID with GPU drivers pre-installed.

        disk_gb : typing.Optional[int]
            Root disk size in gigabytes.

        plan_id : typing.Optional[str]
            Pre-configured GPU plan ID.

        ssh_key_ids : typing.Optional[typing.Sequence[str]]
            SSH key IDs to inject into the VM.

        tags : typing.Optional[typing.Sequence[str]]
            Arbitrary tags for filtering and organization.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[OperationAccepted]
            VM creation accepted.
        """
        _response = self._client_wrapper.httpx_client.request(
            "compute/gpu-vms/",
            method="POST",
            params={
                "workspace_id": workspace_id,
            },
            json={
                "name": name,
                "os_distro": os_distro,
                "os_type": os_type,
                "template_id": template_id,
                "cpu": cpu,
                "ram_mb": ram_mb,
                "disk_gb": disk_gb,
                "gpu_count": gpu_count,
                "gpu_model": gpu_model,
                "plan_id": plan_id,
                "ssh_key_ids": ssh_key_ids,
                "tags": tags,
            },
            headers={
                "content-type": "application/json",
                "X-Idempotency-Key": str(idempotency_key) if idempotency_key is not None else None,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    OperationAccepted,
                    parse_obj_as(
                        type_=OperationAccepted,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_gpu_vm(
        self, vm_id: str, *, workspace_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[GpuVm]:
        """
        Returns a single GPU VM. Requires scope: vm.read.

        Parameters
        ----------
        vm_id : str
            Virtual machine ID.

        workspace_id : str
            The workspace ID to scope this request to.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[GpuVm]
            GPU VM returned successfully.
        """
        _response = self._client_wrapper.httpx_client.request(
            f"compute/gpu-vms/{encode_path_param(vm_id)}",
            method="GET",
            params={
                "workspace_id": workspace_id,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GpuVm,
                    parse_obj_as(
                        type_=GpuVm,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def delete_gpu_vm(
        self,
        vm_id: str,
        *,
        workspace_id: str,
        idempotency_key: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[OperationAccepted]:
        """
        Deletes a GPU VM. Returns an operation you can poll for status. Requires scope: vm.write.

        Parameters
        ----------
        vm_id : str
            Virtual machine ID.

        workspace_id : str
            The workspace ID to scope this request to.

        idempotency_key : str
            Unique key used to safely retry write operations.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[OperationAccepted]
            VM deletion accepted.
        """
        _response = self._client_wrapper.httpx_client.request(
            f"compute/gpu-vms/{encode_path_param(vm_id)}",
            method="DELETE",
            params={
                "workspace_id": workspace_id,
            },
            headers={
                "X-Idempotency-Key": str(idempotency_key) if idempotency_key is not None else None,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    OperationAccepted,
                    parse_obj_as(
                        type_=OperationAccepted,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def update_gpu_vm(
        self,
        vm_id: str,
        *,
        workspace_id: str,
        name: typing.Optional[str] = OMIT,
        tags: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[GpuVm]:
        """
        Updates mutable properties of a GPU VM. Requires scope: vm.write.

        Parameters
        ----------
        vm_id : str
            Virtual machine ID.

        workspace_id : str
            The workspace ID to scope this request to.

        name : typing.Optional[str]
            New display name for the VM.

        tags : typing.Optional[typing.Sequence[str]]
            Updated tags. Replaces all existing tags.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[GpuVm]
            GPU VM updated successfully.
        """
        _response = self._client_wrapper.httpx_client.request(
            f"compute/gpu-vms/{encode_path_param(vm_id)}",
            method="PATCH",
            params={
                "workspace_id": workspace_id,
            },
            json={
                "name": name,
                "tags": tags,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GpuVm,
                    parse_obj_as(
                        type_=GpuVm,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def start_gpu_vm(
        self,
        vm_id: str,
        *,
        workspace_id: str,
        idempotency_key: str,
        force: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[OperationAccepted]:
        """
        Starts a stopped GPU VM. Requires scope: vm.write.

        Parameters
        ----------
        vm_id : str
            Virtual machine ID.

        workspace_id : str
            The workspace ID to scope this request to.

        idempotency_key : str
            Unique key used to safely retry write operations.

        force : typing.Optional[bool]
            Force the action even if the VM is in a transitional state.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[OperationAccepted]
            VM start accepted.
        """
        _response = self._client_wrapper.httpx_client.request(
            f"compute/gpu-vms/{encode_path_param(vm_id)}/actions/start",
            method="POST",
            params={
                "workspace_id": workspace_id,
            },
            json={
                "force": force,
            },
            headers={
                "content-type": "application/json",
                "X-Idempotency-Key": str(idempotency_key) if idempotency_key is not None else None,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    OperationAccepted,
                    parse_obj_as(
                        type_=OperationAccepted,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def stop_gpu_vm(
        self,
        vm_id: str,
        *,
        workspace_id: str,
        idempotency_key: str,
        force: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[OperationAccepted]:
        """
        Stops a running GPU VM. Requires scope: vm.write.

        Parameters
        ----------
        vm_id : str
            Virtual machine ID.

        workspace_id : str
            The workspace ID to scope this request to.

        idempotency_key : str
            Unique key used to safely retry write operations.

        force : typing.Optional[bool]
            Force the action even if the VM is in a transitional state.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[OperationAccepted]
            VM stop accepted.
        """
        _response = self._client_wrapper.httpx_client.request(
            f"compute/gpu-vms/{encode_path_param(vm_id)}/actions/stop",
            method="POST",
            params={
                "workspace_id": workspace_id,
            },
            json={
                "force": force,
            },
            headers={
                "content-type": "application/json",
                "X-Idempotency-Key": str(idempotency_key) if idempotency_key is not None else None,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    OperationAccepted,
                    parse_obj_as(
                        type_=OperationAccepted,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def reboot_gpu_vm(
        self,
        vm_id: str,
        *,
        workspace_id: str,
        idempotency_key: str,
        force: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[OperationAccepted]:
        """
        Reboots a GPU VM. Requires scope: vm.write.

        Parameters
        ----------
        vm_id : str
            Virtual machine ID.

        workspace_id : str
            The workspace ID to scope this request to.

        idempotency_key : str
            Unique key used to safely retry write operations.

        force : typing.Optional[bool]
            Force the action even if the VM is in a transitional state.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[OperationAccepted]
            VM reboot accepted.
        """
        _response = self._client_wrapper.httpx_client.request(
            f"compute/gpu-vms/{encode_path_param(vm_id)}/actions/reboot",
            method="POST",
            params={
                "workspace_id": workspace_id,
            },
            json={
                "force": force,
            },
            headers={
                "content-type": "application/json",
                "X-Idempotency-Key": str(idempotency_key) if idempotency_key is not None else None,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    OperationAccepted,
                    parse_obj_as(
                        type_=OperationAccepted,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_gpu_vm_metrics(
        self, vm_id: str, *, workspace_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[VmMetrics]:
        """
        Returns current resource-usage metrics for a GPU VM. Requires scope: vm.read.

        Parameters
        ----------
        vm_id : str
            Virtual machine ID.

        workspace_id : str
            The workspace ID to scope this request to.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[VmMetrics]
            VM metrics returned successfully.
        """
        _response = self._client_wrapper.httpx_client.request(
            f"compute/gpu-vms/{encode_path_param(vm_id)}/metrics",
            method="GET",
            params={
                "workspace_id": workspace_id,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    VmMetrics,
                    parse_obj_as(
                        type_=VmMetrics,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def list_gpu_vm_network_interfaces(
        self, vm_id: str, *, workspace_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[typing.List[NetworkInterface]]:
        """
        Returns network interfaces attached to a GPU VM. Requires scope: vm.read.

        Parameters
        ----------
        vm_id : str
            Virtual machine ID.

        workspace_id : str
            The workspace ID to scope this request to.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[typing.List[NetworkInterface]]
            Network interfaces returned successfully.
        """
        _response = self._client_wrapper.httpx_client.request(
            f"compute/gpu-vms/{encode_path_param(vm_id)}/network-interfaces",
            method="GET",
            params={
                "workspace_id": workspace_id,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.List[NetworkInterface],
                    parse_obj_as(
                        type_=typing.List[NetworkInterface],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def attach_gpu_vm_network(
        self,
        vm_id: str,
        *,
        workspace_id: str,
        idempotency_key: str,
        network_id: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[NetworkInterface]:
        """
        Attaches a network to a GPU VM. Requires scope: vm.write.

        Parameters
        ----------
        vm_id : str
            Virtual machine ID.

        workspace_id : str
            The workspace ID to scope this request to.

        idempotency_key : str
            Unique key used to safely retry write operations.

        network_id : str
            ID of the network to attach.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[NetworkInterface]
            Network attached successfully.
        """
        _response = self._client_wrapper.httpx_client.request(
            f"compute/gpu-vms/{encode_path_param(vm_id)}/network-interfaces",
            method="POST",
            params={
                "workspace_id": workspace_id,
            },
            json={
                "network_id": network_id,
            },
            headers={
                "content-type": "application/json",
                "X-Idempotency-Key": str(idempotency_key) if idempotency_key is not None else None,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    NetworkInterface,
                    parse_obj_as(
                        type_=NetworkInterface,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def detach_gpu_vm_network(
        self,
        vm_id: str,
        interface_id: str,
        *,
        workspace_id: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[DeleteResponse]:
        """
        Detaches a network interface from a GPU VM. Requires scope: vm.write.

        Parameters
        ----------
        vm_id : str
            Virtual machine ID.

        interface_id : str
            Network interface ID.

        workspace_id : str
            The workspace ID to scope this request to.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[DeleteResponse]
            Network detached successfully.
        """
        _response = self._client_wrapper.httpx_client.request(
            f"compute/gpu-vms/{encode_path_param(vm_id)}/network-interfaces/{encode_path_param(interface_id)}",
            method="DELETE",
            params={
                "workspace_id": workspace_id,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    DeleteResponse,
                    parse_obj_as(
                        type_=DeleteResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawGpuVmsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list_gpu_vms(
        self, *, workspace_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[typing.List[GpuVm]]:
        """
        Returns all GPU VMs in the workspace. Requires scope: vm.read.

        Parameters
        ----------
        workspace_id : str
            The workspace ID to scope this request to.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[typing.List[GpuVm]]
            GPU VMs returned successfully.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "compute/gpu-vms/",
            method="GET",
            params={
                "workspace_id": workspace_id,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.List[GpuVm],
                    parse_obj_as(
                        type_=typing.List[GpuVm],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def create_gpu_vm(
        self,
        *,
        workspace_id: str,
        idempotency_key: str,
        name: str,
        os_distro: str,
        os_type: CreateGpuVmRequestOsType,
        cpu: int,
        ram_mb: int,
        gpu_count: int,
        gpu_model: str,
        template_id: typing.Optional[str] = OMIT,
        disk_gb: typing.Optional[int] = OMIT,
        plan_id: typing.Optional[str] = OMIT,
        ssh_key_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        tags: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[OperationAccepted]:
        """
        Creates a GPU VM. Returns an operation you can poll for status. Requires scope: vm.write.

        Parameters
        ----------
        workspace_id : str
            The workspace ID to scope this request to.

        idempotency_key : str
            Unique key used to safely retry write operations.

        name : str
            Display name for the virtual machine.

        os_distro : str
            Operating system distribution (e.g. ubuntu, centos, debian, rocky).

        os_type : CreateGpuVmRequestOsType
            Operating system family.

        cpu : int
            Number of vCPUs.

        ram_mb : int
            RAM in megabytes.

        gpu_count : int
            Number of GPUs to attach.

        gpu_model : str
            GPU model (e.g. A100, H100, L40S, RTX4090).

        template_id : typing.Optional[str]
            OS template or image ID with GPU drivers pre-installed.

        disk_gb : typing.Optional[int]
            Root disk size in gigabytes.

        plan_id : typing.Optional[str]
            Pre-configured GPU plan ID.

        ssh_key_ids : typing.Optional[typing.Sequence[str]]
            SSH key IDs to inject into the VM.

        tags : typing.Optional[typing.Sequence[str]]
            Arbitrary tags for filtering and organization.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[OperationAccepted]
            VM creation accepted.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "compute/gpu-vms/",
            method="POST",
            params={
                "workspace_id": workspace_id,
            },
            json={
                "name": name,
                "os_distro": os_distro,
                "os_type": os_type,
                "template_id": template_id,
                "cpu": cpu,
                "ram_mb": ram_mb,
                "disk_gb": disk_gb,
                "gpu_count": gpu_count,
                "gpu_model": gpu_model,
                "plan_id": plan_id,
                "ssh_key_ids": ssh_key_ids,
                "tags": tags,
            },
            headers={
                "content-type": "application/json",
                "X-Idempotency-Key": str(idempotency_key) if idempotency_key is not None else None,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    OperationAccepted,
                    parse_obj_as(
                        type_=OperationAccepted,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_gpu_vm(
        self, vm_id: str, *, workspace_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[GpuVm]:
        """
        Returns a single GPU VM. Requires scope: vm.read.

        Parameters
        ----------
        vm_id : str
            Virtual machine ID.

        workspace_id : str
            The workspace ID to scope this request to.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[GpuVm]
            GPU VM returned successfully.
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"compute/gpu-vms/{encode_path_param(vm_id)}",
            method="GET",
            params={
                "workspace_id": workspace_id,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GpuVm,
                    parse_obj_as(
                        type_=GpuVm,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def delete_gpu_vm(
        self,
        vm_id: str,
        *,
        workspace_id: str,
        idempotency_key: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[OperationAccepted]:
        """
        Deletes a GPU VM. Returns an operation you can poll for status. Requires scope: vm.write.

        Parameters
        ----------
        vm_id : str
            Virtual machine ID.

        workspace_id : str
            The workspace ID to scope this request to.

        idempotency_key : str
            Unique key used to safely retry write operations.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[OperationAccepted]
            VM deletion accepted.
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"compute/gpu-vms/{encode_path_param(vm_id)}",
            method="DELETE",
            params={
                "workspace_id": workspace_id,
            },
            headers={
                "X-Idempotency-Key": str(idempotency_key) if idempotency_key is not None else None,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    OperationAccepted,
                    parse_obj_as(
                        type_=OperationAccepted,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def update_gpu_vm(
        self,
        vm_id: str,
        *,
        workspace_id: str,
        name: typing.Optional[str] = OMIT,
        tags: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[GpuVm]:
        """
        Updates mutable properties of a GPU VM. Requires scope: vm.write.

        Parameters
        ----------
        vm_id : str
            Virtual machine ID.

        workspace_id : str
            The workspace ID to scope this request to.

        name : typing.Optional[str]
            New display name for the VM.

        tags : typing.Optional[typing.Sequence[str]]
            Updated tags. Replaces all existing tags.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[GpuVm]
            GPU VM updated successfully.
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"compute/gpu-vms/{encode_path_param(vm_id)}",
            method="PATCH",
            params={
                "workspace_id": workspace_id,
            },
            json={
                "name": name,
                "tags": tags,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GpuVm,
                    parse_obj_as(
                        type_=GpuVm,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def start_gpu_vm(
        self,
        vm_id: str,
        *,
        workspace_id: str,
        idempotency_key: str,
        force: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[OperationAccepted]:
        """
        Starts a stopped GPU VM. Requires scope: vm.write.

        Parameters
        ----------
        vm_id : str
            Virtual machine ID.

        workspace_id : str
            The workspace ID to scope this request to.

        idempotency_key : str
            Unique key used to safely retry write operations.

        force : typing.Optional[bool]
            Force the action even if the VM is in a transitional state.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[OperationAccepted]
            VM start accepted.
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"compute/gpu-vms/{encode_path_param(vm_id)}/actions/start",
            method="POST",
            params={
                "workspace_id": workspace_id,
            },
            json={
                "force": force,
            },
            headers={
                "content-type": "application/json",
                "X-Idempotency-Key": str(idempotency_key) if idempotency_key is not None else None,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    OperationAccepted,
                    parse_obj_as(
                        type_=OperationAccepted,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def stop_gpu_vm(
        self,
        vm_id: str,
        *,
        workspace_id: str,
        idempotency_key: str,
        force: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[OperationAccepted]:
        """
        Stops a running GPU VM. Requires scope: vm.write.

        Parameters
        ----------
        vm_id : str
            Virtual machine ID.

        workspace_id : str
            The workspace ID to scope this request to.

        idempotency_key : str
            Unique key used to safely retry write operations.

        force : typing.Optional[bool]
            Force the action even if the VM is in a transitional state.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[OperationAccepted]
            VM stop accepted.
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"compute/gpu-vms/{encode_path_param(vm_id)}/actions/stop",
            method="POST",
            params={
                "workspace_id": workspace_id,
            },
            json={
                "force": force,
            },
            headers={
                "content-type": "application/json",
                "X-Idempotency-Key": str(idempotency_key) if idempotency_key is not None else None,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    OperationAccepted,
                    parse_obj_as(
                        type_=OperationAccepted,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def reboot_gpu_vm(
        self,
        vm_id: str,
        *,
        workspace_id: str,
        idempotency_key: str,
        force: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[OperationAccepted]:
        """
        Reboots a GPU VM. Requires scope: vm.write.

        Parameters
        ----------
        vm_id : str
            Virtual machine ID.

        workspace_id : str
            The workspace ID to scope this request to.

        idempotency_key : str
            Unique key used to safely retry write operations.

        force : typing.Optional[bool]
            Force the action even if the VM is in a transitional state.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[OperationAccepted]
            VM reboot accepted.
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"compute/gpu-vms/{encode_path_param(vm_id)}/actions/reboot",
            method="POST",
            params={
                "workspace_id": workspace_id,
            },
            json={
                "force": force,
            },
            headers={
                "content-type": "application/json",
                "X-Idempotency-Key": str(idempotency_key) if idempotency_key is not None else None,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    OperationAccepted,
                    parse_obj_as(
                        type_=OperationAccepted,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_gpu_vm_metrics(
        self, vm_id: str, *, workspace_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[VmMetrics]:
        """
        Returns current resource-usage metrics for a GPU VM. Requires scope: vm.read.

        Parameters
        ----------
        vm_id : str
            Virtual machine ID.

        workspace_id : str
            The workspace ID to scope this request to.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[VmMetrics]
            VM metrics returned successfully.
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"compute/gpu-vms/{encode_path_param(vm_id)}/metrics",
            method="GET",
            params={
                "workspace_id": workspace_id,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    VmMetrics,
                    parse_obj_as(
                        type_=VmMetrics,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def list_gpu_vm_network_interfaces(
        self, vm_id: str, *, workspace_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[typing.List[NetworkInterface]]:
        """
        Returns network interfaces attached to a GPU VM. Requires scope: vm.read.

        Parameters
        ----------
        vm_id : str
            Virtual machine ID.

        workspace_id : str
            The workspace ID to scope this request to.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[typing.List[NetworkInterface]]
            Network interfaces returned successfully.
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"compute/gpu-vms/{encode_path_param(vm_id)}/network-interfaces",
            method="GET",
            params={
                "workspace_id": workspace_id,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.List[NetworkInterface],
                    parse_obj_as(
                        type_=typing.List[NetworkInterface],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def attach_gpu_vm_network(
        self,
        vm_id: str,
        *,
        workspace_id: str,
        idempotency_key: str,
        network_id: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[NetworkInterface]:
        """
        Attaches a network to a GPU VM. Requires scope: vm.write.

        Parameters
        ----------
        vm_id : str
            Virtual machine ID.

        workspace_id : str
            The workspace ID to scope this request to.

        idempotency_key : str
            Unique key used to safely retry write operations.

        network_id : str
            ID of the network to attach.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[NetworkInterface]
            Network attached successfully.
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"compute/gpu-vms/{encode_path_param(vm_id)}/network-interfaces",
            method="POST",
            params={
                "workspace_id": workspace_id,
            },
            json={
                "network_id": network_id,
            },
            headers={
                "content-type": "application/json",
                "X-Idempotency-Key": str(idempotency_key) if idempotency_key is not None else None,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    NetworkInterface,
                    parse_obj_as(
                        type_=NetworkInterface,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def detach_gpu_vm_network(
        self,
        vm_id: str,
        interface_id: str,
        *,
        workspace_id: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[DeleteResponse]:
        """
        Detaches a network interface from a GPU VM. Requires scope: vm.write.

        Parameters
        ----------
        vm_id : str
            Virtual machine ID.

        interface_id : str
            Network interface ID.

        workspace_id : str
            The workspace ID to scope this request to.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[DeleteResponse]
            Network detached successfully.
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"compute/gpu-vms/{encode_path_param(vm_id)}/network-interfaces/{encode_path_param(interface_id)}",
            method="DELETE",
            params={
                "workspace_id": workspace_id,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    DeleteResponse,
                    parse_obj_as(
                        type_=DeleteResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
