# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .backup_policy_schedule import BackupPolicySchedule
from .backup_status import BackupStatus


class BackupPolicy(UniversalBaseModel):
    organization_id: str
    organization_name: typing.Optional[str] = None
    workspace_id: str
    workspace_name: typing.Optional[str] = None
    policy_id: str
    vm_id: str
    vm_name: typing.Optional[str] = None
    os_type: typing.Optional[str] = None
    os_distro: typing.Optional[str] = None
    template_id: typing.Optional[str] = None
    enabled: bool
    schedule: BackupPolicySchedule
    retention_days: int
    full_backup_interval_days: int
    incremental_enabled: bool
    storage_backend: str
    next_run_at: typing.Optional[dt.datetime] = None
    last_run_at: typing.Optional[dt.datetime] = None
    last_status: typing.Optional[BackupStatus] = None
    created_at: dt.datetime
    updated_at: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
