# Originally generated by Fern; hand-modified for IBEE 0.4.0 (listed in .fernignore).
#
# The eligibility route returns the billing service's full decision. Fields beyond
# the published contract are typed here as optional so callers can rely on them;
# they are not yet part of the published API contract and may change.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .billing_eligibility_billing_mode import BillingEligibilityBillingMode
from .billing_eligibility_billing_state import BillingEligibilityBillingState
from .billing_eligibility_enforcement_source import BillingEligibilityEnforcementSource
from .billing_eligibility_operation import BillingEligibilityOperation
from .billing_eligibility_service_enforcement_state import BillingEligibilityServiceEnforcementState


class BillingEligibility(UniversalBaseModel):
    organization_id: str
    allowed: bool = pydantic.Field()
    """
    Continue only when this value is exactly true.
    """

    reason: str = pydantic.Field()
    """
    Stable machine-readable decision reason (an open set; for example ``ok``,
    ``insufficient_balance``, ``initial_topup_required``).
    """

    billing_mode: typing.Optional[BillingEligibilityBillingMode] = None
    billing_state: typing.Optional[BillingEligibilityBillingState] = None
    currency: typing.Optional[str] = None
    sku_code: typing.Optional[str] = pydantic.Field(default=None)
    """
    SKU billing evaluated, upper-cased by billing.
    """

    estimated_cost_minor: typing.Optional[int] = None
    effective_balance_minor: typing.Optional[int] = pydantic.Field(default=None)
    """
    Spendable wallet balance (prepaid organizations).
    """

    credit_headroom_minor: typing.Optional[int] = pydantic.Field(default=None)
    """
    Remaining credit (postpaid organizations).
    """

    evaluated_at: typing.Optional[dt.datetime] = None
    service_enforcement_state: typing.Optional[BillingEligibilityServiceEnforcementState] = None
    enforcement_revision: typing.Optional[int] = None
    enforcement_source: typing.Optional[BillingEligibilityEnforcementSource] = None
    enforcement_reason_code: typing.Optional[str] = None
    operation: typing.Optional[BillingEligibilityOperation] = pydantic.Field(default=None)
    """
    The operation that was evaluated (``CREATE_RESOURCE`` unless requested otherwise).
    """

    allowed_operations: typing.Optional[typing.List[str]] = None
    resource_limits: typing.Optional[typing.Dict[str, int]] = pydantic.Field(default=None)
    """
    Per-resource-type limits; a missing key or -1 means unlimited.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
