# This file was auto-generated by Fern from our API Definition.

import typing

CloudVmStatus = typing.Union[
    typing.Literal[
        "pending",
        "creating",
        "provisioning",
        "configuring",
        "running",
        "starting",
        "stopping",
        "stopped",
        "rebooting",
        "resizing",
        "attaching_volume",
        "detaching_volume",
        "resizing_plan",
        "resizing_disk",
        "deleting",
        "deleted",
        "error",
    ],
    typing.Any,
]
