# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .billing_interval import BillingInterval
from .compute_plan_pricing_status import ComputePlanPricingStatus
from .vm_type import VmType


class ComputePlan(UniversalBaseModel):
    plan_id: str = pydantic.Field()
    """
    Plan ID accepted by VM creation.
    """

    vm_type: VmType
    name: str
    code: str
    cpu: int
    ram_mb: int
    disk_gb: int
    gpu_count: int
    gpu_model: typing.Optional[str] = None
    gpu_memory_gb: typing.Optional[float] = None
    selectable: bool
    pricing_status: ComputePlanPricingStatus
    currency: str
    billing_interval: BillingInterval
    hourly_price_minor: typing.Optional[int] = None
    monthly_price_minor: typing.Optional[int] = None
    site_id: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
