# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .create_nat_port_forwarding_rule_request_protocol import CreateNatPortForwardingRuleRequestProtocol


class CreateNatPortForwardingRuleRequest(UniversalBaseModel):
    name: str
    protocol: typing.Optional[CreateNatPortForwardingRuleRequestProtocol] = None
    external_port: int
    internal_ip: str
    internal_port: int
    note: typing.Optional[str] = None
    enabled: typing.Optional[bool] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
