# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .firewall_rule import FirewallRule


class FirewallGroup(UniversalBaseModel):
    firewall_group_id: str
    organization_id: str
    workspace_id: str
    workspace_name: typing.Optional[str] = None
    name: str
    description: typing.Optional[str] = None
    is_default: bool
    status: str
    linked_instance_count: typing.Optional[int] = None
    rules: typing.List[FirewallRule]
    created_at: dt.datetime
    updated_at: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
