# This file was auto-generated by Fern from our API Definition.

import typing

LoadBalancerRoutingAlgorithm = typing.Union[
    typing.Literal["round_robin", "least_request", "random", "consistent_hash"], typing.Any
]
