# This file was auto-generated by Fern from our API Definition.

import typing

LoadBalancerStatus = typing.Union[typing.Literal["provisioning", "active", "failed", "deleting", "deleted"], typing.Any]
