# Originally generated by Fern; hand-modified for IBEE 0.4.0 (listed in .fernignore).

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from .create_nat_port_forwarding_rule_request import CreateNatPortForwardingRuleRequest
from .networking_resource_status import NetworkingResourceStatus


class NatPortForwardingRule(CreateNatPortForwardingRuleRequest):
    port_forward_rule_id: str
    vpc_id: str
    nat_gateway_id: str
    organization_id: typing.Optional[str] = None
    workspace_id: typing.Optional[str] = None
    site_id: typing.Optional[str] = None
    status: NetworkingResourceStatus
    error_message: typing.Optional[str] = None
    target_type: typing.Optional[str] = pydantic.Field(default=None)
    """
    ``vm`` (a NAT-connected VM) or ``vip`` (a MetalLB virtual IP). Not yet part of the published API contract; behaviour may change.
    """

    target_vm_ids: typing.Optional[typing.List[str]] = None
    network_allocation_id: typing.Optional[str] = None
    vm_id: typing.Optional[str] = None
    created_at: dt.datetime
    updated_at: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
