# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .network_interface_status import NetworkInterfaceStatus


class NetworkInterface(UniversalBaseModel):
    id: typing.Optional[str] = None
    network_id: typing.Optional[str] = None
    mac_address: typing.Optional[str] = None
    private_ip: typing.Optional[str] = None
    status: typing.Optional[NetworkInterfaceStatus] = None
    created_at: typing.Optional[dt.datetime] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
