# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .network_allocation_connectivity import NetworkAllocationConnectivity


class NetworkAllocation(UniversalBaseModel):
    allocation_id: str
    vpc_id: str
    subnet_id: str
    vm_id: str
    connectivity: NetworkAllocationConnectivity
    private_ip: str
    prefix_length: int
    subnet_mask: str
    gateway: str
    dns: typing.List[str]
    public_ip_id: typing.Optional[str] = None
    public_ip: typing.Optional[str] = None
    nat_gateway_id: typing.Optional[str] = None
    nat_public_ip: typing.Optional[str] = None
    status: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
