# This file was auto-generated by Fern from our API Definition.

import typing

OperationStatusStatus = typing.Union[
    typing.Literal["accepted", "running", "waiting", "compensating", "succeeded", "failed", "cancelled", "timed_out"],
    typing.Any,
]
