# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class VmEvent(UniversalBaseModel):
    organization_id: str
    organization_name: typing.Optional[str] = None
    workspace_id: str
    workspace_name: typing.Optional[str] = None
    vm_id: str
    operation_id: typing.Optional[str] = None
    event_type: str
    message: str
    payload: typing.Dict[str, typing.Any]
    created_at: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
