# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .create_l4load_balancer_request_protocol import CreateL4LoadBalancerRequestProtocol
    from .create_l7load_balancer_request_custom_domain import CreateL7LoadBalancerRequestCustomDomain
    from .create_l7load_balancer_request_protocol import CreateL7LoadBalancerRequestProtocol
    from .list_load_balancers_request_layer import ListLoadBalancersRequestLayer
    from .update_l7load_balancer_request_custom_domain import UpdateL7LoadBalancerRequestCustomDomain
_dynamic_imports: typing.Dict[str, str] = {
    "CreateL4LoadBalancerRequestProtocol": ".create_l4load_balancer_request_protocol",
    "CreateL7LoadBalancerRequestCustomDomain": ".create_l7load_balancer_request_custom_domain",
    "CreateL7LoadBalancerRequestProtocol": ".create_l7load_balancer_request_protocol",
    "ListLoadBalancersRequestLayer": ".list_load_balancers_request_layer",
    "UpdateL7LoadBalancerRequestCustomDomain": ".update_l7load_balancer_request_custom_domain",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "CreateL4LoadBalancerRequestProtocol",
    "CreateL7LoadBalancerRequestCustomDomain",
    "CreateL7LoadBalancerRequestProtocol",
    "ListLoadBalancersRequestLayer",
    "UpdateL7LoadBalancerRequestCustomDomain",
]
