# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.vm_console_close import VmConsoleClose
from ..types.vm_console_session import VmConsoleSession
from ..types.vm_console_session_status import VmConsoleSessionStatus
from ..types.vm_type import VmType
from .raw_client import AsyncRawVmConsoleClient, RawVmConsoleClient
from .types.vm_console_session_create_request_console_type import VmConsoleSessionCreateRequestConsoleType

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class VmConsoleClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawVmConsoleClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawVmConsoleClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawVmConsoleClient
        """
        return self._raw_client

    def create_vm_console_session(
        self,
        *,
        workspace_id: str,
        vm_id: str,
        vm_type: typing.Optional[VmType] = OMIT,
        console_type: typing.Optional[VmConsoleSessionCreateRequestConsoleType] = OMIT,
        requested_by: typing.Optional[str] = OMIT,
        user_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> VmConsoleSession:
        """
        Creates a short-lived graphical console session for a cloud or GPU VM. The returned connect URL contains an expiring token; do not log or persist it. Requires scope: vm.write.

        Parameters
        ----------
        workspace_id : str
            The workspace ID to scope this request to.

        vm_id : str

        vm_type : typing.Optional[VmType]

        console_type : typing.Optional[VmConsoleSessionCreateRequestConsoleType]

        requested_by : typing.Optional[str]

        user_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        VmConsoleSession
            Console session created successfully.

        Examples
        --------
        from ibee import Ibee

        client = Ibee(
            token="YOUR_TOKEN",
        )
        client.vm_console.create_vm_console_session(
            workspace_id="workspace_id",
            vm_id="vm_id",
        )
        """
        _response = self._raw_client.create_vm_console_session(
            workspace_id=workspace_id,
            vm_id=vm_id,
            vm_type=vm_type,
            console_type=console_type,
            requested_by=requested_by,
            user_id=user_id,
            request_options=request_options,
        )
        return _response.data

    def get_vm_console_session(
        self, session_id: str, *, workspace_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> VmConsoleSessionStatus:
        """
        Returns the status of a workspace-owned console session. Requires scope: vm.read.

        Parameters
        ----------
        session_id : str
            VM console session ID.

        workspace_id : str
            The workspace ID to scope this request to.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        VmConsoleSessionStatus
            Console session status returned successfully.

        Examples
        --------
        from ibee import Ibee

        client = Ibee(
            token="YOUR_TOKEN",
        )
        client.vm_console.get_vm_console_session(
            session_id="session_id",
            workspace_id="workspace_id",
        )
        """
        _response = self._raw_client.get_vm_console_session(
            session_id, workspace_id=workspace_id, request_options=request_options
        )
        return _response.data

    def close_vm_console_session(
        self,
        session_id: str,
        *,
        workspace_id: str,
        reason: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> VmConsoleClose:
        """
        Closes a workspace-owned console session and invalidates its connection token. Requires scope: vm.write.

        Parameters
        ----------
        session_id : str
            VM console session ID.

        workspace_id : str
            The workspace ID to scope this request to.

        reason : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        VmConsoleClose
            Console session closed successfully.

        Examples
        --------
        from ibee import Ibee

        client = Ibee(
            token="YOUR_TOKEN",
        )
        client.vm_console.close_vm_console_session(
            session_id="session_id",
            workspace_id="workspace_id",
        )
        """
        _response = self._raw_client.close_vm_console_session(
            session_id, workspace_id=workspace_id, reason=reason, request_options=request_options
        )
        return _response.data


class AsyncVmConsoleClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawVmConsoleClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawVmConsoleClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawVmConsoleClient
        """
        return self._raw_client

    async def create_vm_console_session(
        self,
        *,
        workspace_id: str,
        vm_id: str,
        vm_type: typing.Optional[VmType] = OMIT,
        console_type: typing.Optional[VmConsoleSessionCreateRequestConsoleType] = OMIT,
        requested_by: typing.Optional[str] = OMIT,
        user_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> VmConsoleSession:
        """
        Creates a short-lived graphical console session for a cloud or GPU VM. The returned connect URL contains an expiring token; do not log or persist it. Requires scope: vm.write.

        Parameters
        ----------
        workspace_id : str
            The workspace ID to scope this request to.

        vm_id : str

        vm_type : typing.Optional[VmType]

        console_type : typing.Optional[VmConsoleSessionCreateRequestConsoleType]

        requested_by : typing.Optional[str]

        user_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        VmConsoleSession
            Console session created successfully.

        Examples
        --------
        import asyncio

        from ibee import AsyncIbee

        client = AsyncIbee(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.vm_console.create_vm_console_session(
                workspace_id="workspace_id",
                vm_id="vm_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_vm_console_session(
            workspace_id=workspace_id,
            vm_id=vm_id,
            vm_type=vm_type,
            console_type=console_type,
            requested_by=requested_by,
            user_id=user_id,
            request_options=request_options,
        )
        return _response.data

    async def get_vm_console_session(
        self, session_id: str, *, workspace_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> VmConsoleSessionStatus:
        """
        Returns the status of a workspace-owned console session. Requires scope: vm.read.

        Parameters
        ----------
        session_id : str
            VM console session ID.

        workspace_id : str
            The workspace ID to scope this request to.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        VmConsoleSessionStatus
            Console session status returned successfully.

        Examples
        --------
        import asyncio

        from ibee import AsyncIbee

        client = AsyncIbee(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.vm_console.get_vm_console_session(
                session_id="session_id",
                workspace_id="workspace_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_vm_console_session(
            session_id, workspace_id=workspace_id, request_options=request_options
        )
        return _response.data

    async def close_vm_console_session(
        self,
        session_id: str,
        *,
        workspace_id: str,
        reason: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> VmConsoleClose:
        """
        Closes a workspace-owned console session and invalidates its connection token. Requires scope: vm.write.

        Parameters
        ----------
        session_id : str
            VM console session ID.

        workspace_id : str
            The workspace ID to scope this request to.

        reason : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        VmConsoleClose
            Console session closed successfully.

        Examples
        --------
        import asyncio

        from ibee import AsyncIbee

        client = AsyncIbee(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.vm_console.close_vm_console_session(
                session_id="session_id",
                workspace_id="workspace_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.close_vm_console_session(
            session_id, workspace_id=workspace_id, reason=reason, request_options=request_options
        )
        return _response.data
