# Originally generated by Fern; hand-modified for IBEE 0.4.0 (listed in .fernignore).

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.load_balancer import LoadBalancer
from ..types.load_balancer_backend import LoadBalancerBackend
from ..types.load_balancer_protocol import LoadBalancerProtocol
from ..types.load_balancer_routing import LoadBalancerRouting
from ..types.load_balancer_rule import LoadBalancerRule
from ..types.load_balancer_status import LoadBalancerStatus
from ..types.load_balancer_status_response import LoadBalancerStatusResponse
from ..types.load_balancer_tls import LoadBalancerTls
from .raw_client import AsyncRawLoadBalancersClient, RawLoadBalancersClient
from .types.create_l4load_balancer_request_protocol import CreateL4LoadBalancerRequestProtocol
from .types.create_l7load_balancer_request_custom_domain import CreateL7LoadBalancerRequestCustomDomain
from .types.create_l7load_balancer_request_protocol import CreateL7LoadBalancerRequestProtocol
from .types.list_load_balancers_request_layer import ListLoadBalancersRequestLayer
from .types.update_l7load_balancer_request_custom_domain import UpdateL7LoadBalancerRequestCustomDomain

from .. import networking_workflows as nw
from ..compute_workflows import clean_kwargs, run_async, run_sync

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class LoadBalancersClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawLoadBalancersClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawLoadBalancersClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawLoadBalancersClient
        """
        return self._raw_client

    def list_load_balancers(
        self,
        *,
        workspace_id: str,
        status: typing.Optional[LoadBalancerStatus] = None,
        layer: typing.Optional[ListLoadBalancersRequestLayer] = None,
        protocol: typing.Optional[LoadBalancerProtocol] = None,
        limit: typing.Optional[int] = None,
        skip: typing.Optional[int] = None,
        include_deleted: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[LoadBalancer]:
        """
        Lists load balancers. Requires scope: load-balancer.read. ``status='deleted'`` implies
        ``include_deleted=True``.

        Parameters
        ----------
        workspace_id : str
            The workspace ID to scope this request to.

        status : typing.Optional[LoadBalancerStatus]
            provisioning, active, failed, deleting or deleted.

        layer : typing.Optional[ListLoadBalancersRequestLayer]
            ``l4`` or ``l7``.

        protocol : typing.Optional[LoadBalancerProtocol]
            L4: tcp or tls_passthrough; L7: http or https.

        limit : typing.Optional[int]
            1-500.

        skip : typing.Optional[int]
            >= 0.

        include_deleted : typing.Optional[bool]
            Include deleted load balancers. Not yet part of the published API contract; behaviour may change.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[LoadBalancer]
        """
        return run_sync(self._raw_client._client_wrapper, nw.list_load_balancers(**clean_kwargs(locals())), request_options)

    def create_l4load_balancer(
        self,
        *,
        workspace_id: str,
        name: str,
        protocol: CreateL4LoadBalancerRequestProtocol,
        backends: typing.Sequence[LoadBalancerBackend],
        routing: typing.Optional[LoadBalancerRouting] = OMIT,
        tls: typing.Optional[LoadBalancerTls] = OMIT,
        policy: typing.Optional[typing.Dict[str, typing.Any]] = None,
        health_check: typing.Optional[typing.Dict[str, typing.Any]] = None,
        observability: typing.Optional[typing.Dict[str, typing.Any]] = None,
        check_billing: bool = False,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> LoadBalancer:
        """
        Creates an L4 (TCP / TLS passthrough) load balancer. Requires scope: load-balancer.write.

        ``tls`` defaults to managed passthrough for ``tls_passthrough``; custom certificates are not supported.
        Sticky sessions are L7 only. The API edge checks billing (SKU LOADBALA-STD).

        Parameters
        ----------
        workspace_id : str
            The workspace ID to scope this request to.

        name : str
            1-128 characters (trimmed).

        protocol : CreateL4LoadBalancerRequestProtocol
            ``tcp`` or ``tls_passthrough``.

        backends : typing.Sequence[LoadBalancerBackend]
            At least one backend: ``type`` service|ip|hostname, ``target``, ``port`` 1-65535, ``weight`` 1-1000
            (default 100), ``tls``. Models or dicts.

        routing : typing.Optional[LoadBalancerRouting]
            ``algorithm``: round_robin, least_request, random or consistent_hash.

        tls : typing.Optional[LoadBalancerTls]
            ``tls_passthrough`` only: mode ``passthrough``, certificate_source ``managed`` (the default).

        policy : typing.Optional[typing.Dict[str, typing.Any]]
            ``{timeout_ms (100-300000), retries: {attempts 1-10, on [...], per_retry_timeout_ms 100-120000},
            proxy_protocol_enabled}``. Not yet part of the published API contract; behaviour may change.

        health_check : typing.Optional[typing.Dict[str, typing.Any]]
            ``{active: {type http|https|tcp, path (not for tcp), interval_ms, timeout_ms (100-120000),
            healthy_threshold, unhealthy_threshold (1-20)}, passive: {...}}``. Not sent unless given (the portal's
            form default is an http check of /health every 10 s). Not yet part of the published API contract;
            behaviour may change.

        observability : typing.Optional[typing.Dict[str, typing.Any]]
            ``{logs_enabled: bool}``. Not yet part of the published API contract; behaviour may change.

        check_billing : bool
            Deprecated no-op. The upstream mutation decides billing and lifecycle admission.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        LoadBalancer
        """
        return run_sync(self._raw_client._client_wrapper, nw.create_load_balancer("l4", **clean_kwargs(locals())), request_options)

    def create_l7load_balancer(
        self,
        *,
        workspace_id: str,
        name: str,
        protocol: CreateL7LoadBalancerRequestProtocol,
        backends: typing.Sequence[LoadBalancerBackend],
        routing: typing.Optional[LoadBalancerRouting] = OMIT,
        tls: typing.Optional[LoadBalancerTls] = OMIT,
        custom_domain: typing.Optional[CreateL7LoadBalancerRequestCustomDomain] = OMIT,
        rules: typing.Optional[typing.Sequence[LoadBalancerRule]] = OMIT,
        policy: typing.Optional[typing.Dict[str, typing.Any]] = None,
        health_check: typing.Optional[typing.Dict[str, typing.Any]] = None,
        observability: typing.Optional[typing.Dict[str, typing.Any]] = None,
        check_billing: bool = False,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> LoadBalancer:
        """
        Creates an L7 (HTTP / HTTPS) load balancer. Requires scope: load-balancer.write.

        ``tls`` defaults to a managed certificate for ``https``; custom certificates are not supported.
        ``custom_domain`` is https only and its CNAME must already point at the IBEE target. The API edge checks
        billing (SKU LOADBALA-STD).

        Parameters
        ----------
        workspace_id : str
            The workspace ID to scope this request to.

        name : str
            1-128 characters (trimmed).

        protocol : CreateL7LoadBalancerRequestProtocol
            ``http`` or ``https``.

        backends : typing.Sequence[LoadBalancerBackend]
            At least one backend: ``type`` service|ip|hostname, ``target``, ``port`` 1-65535, ``weight`` 1-1000
            (default 100), ``tls``. Models or dicts.

        routing : typing.Optional[LoadBalancerRouting]
            ``algorithm`` and optional ``sticky_header`` (for example X-User-ID).

        tls : typing.Optional[LoadBalancerTls]
            ``https`` only: mode ``terminate``, certificate_source ``managed`` (the default).

        custom_domain : typing.Optional[CreateL7LoadBalancerRequestCustomDomain]
            ``{hostname}`` (https only).

        rules : typing.Optional[typing.Sequence[LoadBalancerRule]]
            Path rules: ``priority`` >= 1, ``path_prefix`` starting with '/', optional ``headers`` and ``backends``.

        policy : typing.Optional[typing.Dict[str, typing.Any]]
            ``{timeout_ms (100-300000), retries: {attempts 1-10, on [...], per_retry_timeout_ms 100-120000},
            proxy_protocol_enabled}``. Not yet part of the published API contract; behaviour may change.

        health_check : typing.Optional[typing.Dict[str, typing.Any]]
            ``{active: {type http|https|tcp, path (not for tcp), interval_ms, timeout_ms (100-120000),
            healthy_threshold, unhealthy_threshold (1-20)}, passive: {...}}``. Not sent unless given (the portal's
            form default is an http check of /health every 10 s). Not yet part of the published API contract;
            behaviour may change.

        observability : typing.Optional[typing.Dict[str, typing.Any]]
            ``{logs_enabled: bool}``. Not yet part of the published API contract; behaviour may change.

        check_billing : bool
            Deprecated no-op. The upstream mutation decides billing and lifecycle admission.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        LoadBalancer
        """
        return run_sync(self._raw_client._client_wrapper, nw.create_load_balancer("l7", **clean_kwargs(locals())), request_options)

    def get_load_balancer(
        self,
        load_balancer_id: str,
        *,
        workspace_id: str,
        include_deleted: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> LoadBalancer:
        """
        Returns a load balancer. Requires scope: load-balancer.read. Routing, policy, health check and TLS settings
        are not returned by the API.

        Parameters
        ----------
        load_balancer_id : str
            Load balancer ID.

        workspace_id : str
            The workspace ID to scope this request to.

        include_deleted : typing.Optional[bool]
            Also return a deleted load balancer. Not yet part of the published API contract; behaviour may change.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        LoadBalancer
        """
        return run_sync(self._raw_client._client_wrapper, nw.get_load_balancer(**clean_kwargs(locals())), request_options)

    def delete_load_balancer(
        self, load_balancer_id: str, *, workspace_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Parameters
        ----------
        load_balancer_id : str
            Load balancer ID.

        workspace_id : str
            The workspace ID to scope this request to.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from ibee import Ibee

        client = Ibee(
            token="YOUR_TOKEN",
        )
        client.load_balancers.delete_load_balancer(
            load_balancer_id="load_balancer_id",
            workspace_id="workspace_id",
        )
        """
        _response = self._raw_client.delete_load_balancer(
            load_balancer_id, workspace_id=workspace_id, request_options=request_options
        )
        return _response.data

    def update_l4load_balancer(
        self,
        load_balancer_id: str,
        *,
        workspace_id: str,
        name: typing.Optional[str] = OMIT,
        backends: typing.Optional[typing.Sequence[LoadBalancerBackend]] = OMIT,
        routing: typing.Optional[LoadBalancerRouting] = OMIT,
        tls: typing.Optional[LoadBalancerTls] = OMIT,
        policy: typing.Optional[typing.Dict[str, typing.Any]] = None,
        health_check: typing.Optional[typing.Dict[str, typing.Any]] = None,
        observability: typing.Optional[typing.Dict[str, typing.Any]] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> LoadBalancer:
        """
        Updates an L4 load balancer. Requires scope: load-balancer.write. At least one field is required; the create
        rules apply.

        Parameters
        ----------
        load_balancer_id : str
            Load balancer ID.

        workspace_id : str
            The workspace ID to scope this request to.

        name : typing.Optional[str]
            1-128 characters.

        backends : typing.Optional[typing.Sequence[LoadBalancerBackend]]
            At least one backend: ``type`` service|ip|hostname, ``target``, ``port`` 1-65535, ``weight`` 1-1000
            (default 100), ``tls``. Models or dicts.

        routing : typing.Optional[LoadBalancerRouting]
            ``algorithm`` (no sticky_header on L4).

        tls : typing.Optional[LoadBalancerTls]
            Managed passthrough only.

        policy : typing.Optional[typing.Dict[str, typing.Any]]
            ``{timeout_ms (100-300000), retries: {attempts 1-10, on [...], per_retry_timeout_ms 100-120000},
            proxy_protocol_enabled}``. Not yet part of the published API contract; behaviour may change.

        health_check : typing.Optional[typing.Dict[str, typing.Any]]
            ``{active: {type http|https|tcp, path (not for tcp), interval_ms, timeout_ms (100-120000),
            healthy_threshold, unhealthy_threshold (1-20)}, passive: {...}}``. Not sent unless given (the portal's
            form default is an http check of /health every 10 s). Not yet part of the published API contract;
            behaviour may change.

        observability : typing.Optional[typing.Dict[str, typing.Any]]
            ``{logs_enabled: bool}``. Not yet part of the published API contract; behaviour may change.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        LoadBalancer
        """
        return run_sync(self._raw_client._client_wrapper, nw.update_load_balancer("l4", **clean_kwargs(locals())), request_options)

    def update_l7load_balancer(
        self,
        load_balancer_id: str,
        *,
        workspace_id: str,
        name: typing.Optional[str] = OMIT,
        backends: typing.Optional[typing.Sequence[LoadBalancerBackend]] = OMIT,
        routing: typing.Optional[LoadBalancerRouting] = OMIT,
        tls: typing.Optional[LoadBalancerTls] = OMIT,
        custom_domain: typing.Optional[UpdateL7LoadBalancerRequestCustomDomain] = OMIT,
        rules: typing.Optional[typing.Sequence[LoadBalancerRule]] = OMIT,
        policy: typing.Optional[typing.Dict[str, typing.Any]] = None,
        health_check: typing.Optional[typing.Dict[str, typing.Any]] = None,
        observability: typing.Optional[typing.Dict[str, typing.Any]] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> LoadBalancer:
        """
        Updates an L7 load balancer. Requires scope: load-balancer.write. At least one field is required;
        ``custom_domain=None`` removes the custom domain.

        Parameters
        ----------
        load_balancer_id : str
            Load balancer ID.

        workspace_id : str
            The workspace ID to scope this request to.

        name : typing.Optional[str]
            1-128 characters.

        backends : typing.Optional[typing.Sequence[LoadBalancerBackend]]
            At least one backend: ``type`` service|ip|hostname, ``target``, ``port`` 1-65535, ``weight`` 1-1000
            (default 100), ``tls``. Models or dicts.

        routing : typing.Optional[LoadBalancerRouting]
            ``algorithm`` and optional ``sticky_header``.

        tls : typing.Optional[LoadBalancerTls]
            Managed terminate only.

        custom_domain : typing.Optional[UpdateL7LoadBalancerRequestCustomDomain]
            ``{hostname}`` to set (https only), ``None`` to clear.

        rules : typing.Optional[typing.Sequence[LoadBalancerRule]]
            Path rules (see create).

        policy : typing.Optional[typing.Dict[str, typing.Any]]
            ``{timeout_ms (100-300000), retries: {attempts 1-10, on [...], per_retry_timeout_ms 100-120000},
            proxy_protocol_enabled}``. Not yet part of the published API contract; behaviour may change.

        health_check : typing.Optional[typing.Dict[str, typing.Any]]
            ``{active: {type http|https|tcp, path (not for tcp), interval_ms, timeout_ms (100-120000),
            healthy_threshold, unhealthy_threshold (1-20)}, passive: {...}}``. Not sent unless given (the portal's
            form default is an http check of /health every 10 s). Not yet part of the published API contract;
            behaviour may change.

        observability : typing.Optional[typing.Dict[str, typing.Any]]
            ``{logs_enabled: bool}``. Not yet part of the published API contract; behaviour may change.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        LoadBalancer
        """
        return run_sync(self._raw_client._client_wrapper, nw.update_load_balancer("l7", **{**clean_kwargs(locals()), "custom_domain": custom_domain}), request_options)

    def get_load_balancer_status(
        self, load_balancer_id: str, *, workspace_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> LoadBalancerStatusResponse:
        """
        Parameters
        ----------
        load_balancer_id : str
            Load balancer ID.

        workspace_id : str
            The workspace ID to scope this request to.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        LoadBalancerStatusResponse
            Load balancer status returned successfully.

        Examples
        --------
        from ibee import Ibee

        client = Ibee(
            token="YOUR_TOKEN",
        )
        client.load_balancers.get_load_balancer_status(
            load_balancer_id="load_balancer_id",
            workspace_id="workspace_id",
        )
        """
        _response = self._raw_client.get_load_balancer_status(
            load_balancer_id, workspace_id=workspace_id, request_options=request_options
        )
        return _response.data


class AsyncLoadBalancersClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawLoadBalancersClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawLoadBalancersClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawLoadBalancersClient
        """
        return self._raw_client

    async def list_load_balancers(
        self,
        *,
        workspace_id: str,
        status: typing.Optional[LoadBalancerStatus] = None,
        layer: typing.Optional[ListLoadBalancersRequestLayer] = None,
        protocol: typing.Optional[LoadBalancerProtocol] = None,
        limit: typing.Optional[int] = None,
        skip: typing.Optional[int] = None,
        include_deleted: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[LoadBalancer]:
        """
        Lists load balancers. Requires scope: load-balancer.read. ``status='deleted'`` implies
        ``include_deleted=True``.

        Parameters
        ----------
        workspace_id : str
            The workspace ID to scope this request to.

        status : typing.Optional[LoadBalancerStatus]
            provisioning, active, failed, deleting or deleted.

        layer : typing.Optional[ListLoadBalancersRequestLayer]
            ``l4`` or ``l7``.

        protocol : typing.Optional[LoadBalancerProtocol]
            L4: tcp or tls_passthrough; L7: http or https.

        limit : typing.Optional[int]
            1-500.

        skip : typing.Optional[int]
            >= 0.

        include_deleted : typing.Optional[bool]
            Include deleted load balancers. Not yet part of the published API contract; behaviour may change.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[LoadBalancer]
        """
        return await run_async(self._raw_client._client_wrapper, nw.list_load_balancers(**clean_kwargs(locals())), request_options)

    async def create_l4load_balancer(
        self,
        *,
        workspace_id: str,
        name: str,
        protocol: CreateL4LoadBalancerRequestProtocol,
        backends: typing.Sequence[LoadBalancerBackend],
        routing: typing.Optional[LoadBalancerRouting] = OMIT,
        tls: typing.Optional[LoadBalancerTls] = OMIT,
        policy: typing.Optional[typing.Dict[str, typing.Any]] = None,
        health_check: typing.Optional[typing.Dict[str, typing.Any]] = None,
        observability: typing.Optional[typing.Dict[str, typing.Any]] = None,
        check_billing: bool = False,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> LoadBalancer:
        """
        Creates an L4 (TCP / TLS passthrough) load balancer. Requires scope: load-balancer.write.

        ``tls`` defaults to managed passthrough for ``tls_passthrough``; custom certificates are not supported.
        Sticky sessions are L7 only. The API edge checks billing (SKU LOADBALA-STD).

        Parameters
        ----------
        workspace_id : str
            The workspace ID to scope this request to.

        name : str
            1-128 characters (trimmed).

        protocol : CreateL4LoadBalancerRequestProtocol
            ``tcp`` or ``tls_passthrough``.

        backends : typing.Sequence[LoadBalancerBackend]
            At least one backend: ``type`` service|ip|hostname, ``target``, ``port`` 1-65535, ``weight`` 1-1000
            (default 100), ``tls``. Models or dicts.

        routing : typing.Optional[LoadBalancerRouting]
            ``algorithm``: round_robin, least_request, random or consistent_hash.

        tls : typing.Optional[LoadBalancerTls]
            ``tls_passthrough`` only: mode ``passthrough``, certificate_source ``managed`` (the default).

        policy : typing.Optional[typing.Dict[str, typing.Any]]
            ``{timeout_ms (100-300000), retries: {attempts 1-10, on [...], per_retry_timeout_ms 100-120000},
            proxy_protocol_enabled}``. Not yet part of the published API contract; behaviour may change.

        health_check : typing.Optional[typing.Dict[str, typing.Any]]
            ``{active: {type http|https|tcp, path (not for tcp), interval_ms, timeout_ms (100-120000),
            healthy_threshold, unhealthy_threshold (1-20)}, passive: {...}}``. Not sent unless given (the portal's
            form default is an http check of /health every 10 s). Not yet part of the published API contract;
            behaviour may change.

        observability : typing.Optional[typing.Dict[str, typing.Any]]
            ``{logs_enabled: bool}``. Not yet part of the published API contract; behaviour may change.

        check_billing : bool
            Deprecated no-op. The upstream mutation decides billing and lifecycle admission.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        LoadBalancer
        """
        return await run_async(self._raw_client._client_wrapper, nw.create_load_balancer("l4", **clean_kwargs(locals())), request_options)

    async def create_l7load_balancer(
        self,
        *,
        workspace_id: str,
        name: str,
        protocol: CreateL7LoadBalancerRequestProtocol,
        backends: typing.Sequence[LoadBalancerBackend],
        routing: typing.Optional[LoadBalancerRouting] = OMIT,
        tls: typing.Optional[LoadBalancerTls] = OMIT,
        custom_domain: typing.Optional[CreateL7LoadBalancerRequestCustomDomain] = OMIT,
        rules: typing.Optional[typing.Sequence[LoadBalancerRule]] = OMIT,
        policy: typing.Optional[typing.Dict[str, typing.Any]] = None,
        health_check: typing.Optional[typing.Dict[str, typing.Any]] = None,
        observability: typing.Optional[typing.Dict[str, typing.Any]] = None,
        check_billing: bool = False,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> LoadBalancer:
        """
        Creates an L7 (HTTP / HTTPS) load balancer. Requires scope: load-balancer.write.

        ``tls`` defaults to a managed certificate for ``https``; custom certificates are not supported.
        ``custom_domain`` is https only and its CNAME must already point at the IBEE target. The API edge checks
        billing (SKU LOADBALA-STD).

        Parameters
        ----------
        workspace_id : str
            The workspace ID to scope this request to.

        name : str
            1-128 characters (trimmed).

        protocol : CreateL7LoadBalancerRequestProtocol
            ``http`` or ``https``.

        backends : typing.Sequence[LoadBalancerBackend]
            At least one backend: ``type`` service|ip|hostname, ``target``, ``port`` 1-65535, ``weight`` 1-1000
            (default 100), ``tls``. Models or dicts.

        routing : typing.Optional[LoadBalancerRouting]
            ``algorithm`` and optional ``sticky_header`` (for example X-User-ID).

        tls : typing.Optional[LoadBalancerTls]
            ``https`` only: mode ``terminate``, certificate_source ``managed`` (the default).

        custom_domain : typing.Optional[CreateL7LoadBalancerRequestCustomDomain]
            ``{hostname}`` (https only).

        rules : typing.Optional[typing.Sequence[LoadBalancerRule]]
            Path rules: ``priority`` >= 1, ``path_prefix`` starting with '/', optional ``headers`` and ``backends``.

        policy : typing.Optional[typing.Dict[str, typing.Any]]
            ``{timeout_ms (100-300000), retries: {attempts 1-10, on [...], per_retry_timeout_ms 100-120000},
            proxy_protocol_enabled}``. Not yet part of the published API contract; behaviour may change.

        health_check : typing.Optional[typing.Dict[str, typing.Any]]
            ``{active: {type http|https|tcp, path (not for tcp), interval_ms, timeout_ms (100-120000),
            healthy_threshold, unhealthy_threshold (1-20)}, passive: {...}}``. Not sent unless given (the portal's
            form default is an http check of /health every 10 s). Not yet part of the published API contract;
            behaviour may change.

        observability : typing.Optional[typing.Dict[str, typing.Any]]
            ``{logs_enabled: bool}``. Not yet part of the published API contract; behaviour may change.

        check_billing : bool
            Deprecated no-op. The upstream mutation decides billing and lifecycle admission.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        LoadBalancer
        """
        return await run_async(self._raw_client._client_wrapper, nw.create_load_balancer("l7", **clean_kwargs(locals())), request_options)

    async def get_load_balancer(
        self,
        load_balancer_id: str,
        *,
        workspace_id: str,
        include_deleted: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> LoadBalancer:
        """
        Returns a load balancer. Requires scope: load-balancer.read. Routing, policy, health check and TLS settings
        are not returned by the API.

        Parameters
        ----------
        load_balancer_id : str
            Load balancer ID.

        workspace_id : str
            The workspace ID to scope this request to.

        include_deleted : typing.Optional[bool]
            Also return a deleted load balancer. Not yet part of the published API contract; behaviour may change.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        LoadBalancer
        """
        return await run_async(self._raw_client._client_wrapper, nw.get_load_balancer(**clean_kwargs(locals())), request_options)

    async def delete_load_balancer(
        self, load_balancer_id: str, *, workspace_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Parameters
        ----------
        load_balancer_id : str
            Load balancer ID.

        workspace_id : str
            The workspace ID to scope this request to.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from ibee import AsyncIbee

        client = AsyncIbee(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.load_balancers.delete_load_balancer(
                load_balancer_id="load_balancer_id",
                workspace_id="workspace_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_load_balancer(
            load_balancer_id, workspace_id=workspace_id, request_options=request_options
        )
        return _response.data

    async def update_l4load_balancer(
        self,
        load_balancer_id: str,
        *,
        workspace_id: str,
        name: typing.Optional[str] = OMIT,
        backends: typing.Optional[typing.Sequence[LoadBalancerBackend]] = OMIT,
        routing: typing.Optional[LoadBalancerRouting] = OMIT,
        tls: typing.Optional[LoadBalancerTls] = OMIT,
        policy: typing.Optional[typing.Dict[str, typing.Any]] = None,
        health_check: typing.Optional[typing.Dict[str, typing.Any]] = None,
        observability: typing.Optional[typing.Dict[str, typing.Any]] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> LoadBalancer:
        """
        Updates an L4 load balancer. Requires scope: load-balancer.write. At least one field is required; the create
        rules apply.

        Parameters
        ----------
        load_balancer_id : str
            Load balancer ID.

        workspace_id : str
            The workspace ID to scope this request to.

        name : typing.Optional[str]
            1-128 characters.

        backends : typing.Optional[typing.Sequence[LoadBalancerBackend]]
            At least one backend: ``type`` service|ip|hostname, ``target``, ``port`` 1-65535, ``weight`` 1-1000
            (default 100), ``tls``. Models or dicts.

        routing : typing.Optional[LoadBalancerRouting]
            ``algorithm`` (no sticky_header on L4).

        tls : typing.Optional[LoadBalancerTls]
            Managed passthrough only.

        policy : typing.Optional[typing.Dict[str, typing.Any]]
            ``{timeout_ms (100-300000), retries: {attempts 1-10, on [...], per_retry_timeout_ms 100-120000},
            proxy_protocol_enabled}``. Not yet part of the published API contract; behaviour may change.

        health_check : typing.Optional[typing.Dict[str, typing.Any]]
            ``{active: {type http|https|tcp, path (not for tcp), interval_ms, timeout_ms (100-120000),
            healthy_threshold, unhealthy_threshold (1-20)}, passive: {...}}``. Not sent unless given (the portal's
            form default is an http check of /health every 10 s). Not yet part of the published API contract;
            behaviour may change.

        observability : typing.Optional[typing.Dict[str, typing.Any]]
            ``{logs_enabled: bool}``. Not yet part of the published API contract; behaviour may change.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        LoadBalancer
        """
        return await run_async(self._raw_client._client_wrapper, nw.update_load_balancer("l4", **clean_kwargs(locals())), request_options)

    async def update_l7load_balancer(
        self,
        load_balancer_id: str,
        *,
        workspace_id: str,
        name: typing.Optional[str] = OMIT,
        backends: typing.Optional[typing.Sequence[LoadBalancerBackend]] = OMIT,
        routing: typing.Optional[LoadBalancerRouting] = OMIT,
        tls: typing.Optional[LoadBalancerTls] = OMIT,
        custom_domain: typing.Optional[UpdateL7LoadBalancerRequestCustomDomain] = OMIT,
        rules: typing.Optional[typing.Sequence[LoadBalancerRule]] = OMIT,
        policy: typing.Optional[typing.Dict[str, typing.Any]] = None,
        health_check: typing.Optional[typing.Dict[str, typing.Any]] = None,
        observability: typing.Optional[typing.Dict[str, typing.Any]] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> LoadBalancer:
        """
        Updates an L7 load balancer. Requires scope: load-balancer.write. At least one field is required;
        ``custom_domain=None`` removes the custom domain.

        Parameters
        ----------
        load_balancer_id : str
            Load balancer ID.

        workspace_id : str
            The workspace ID to scope this request to.

        name : typing.Optional[str]
            1-128 characters.

        backends : typing.Optional[typing.Sequence[LoadBalancerBackend]]
            At least one backend: ``type`` service|ip|hostname, ``target``, ``port`` 1-65535, ``weight`` 1-1000
            (default 100), ``tls``. Models or dicts.

        routing : typing.Optional[LoadBalancerRouting]
            ``algorithm`` and optional ``sticky_header``.

        tls : typing.Optional[LoadBalancerTls]
            Managed terminate only.

        custom_domain : typing.Optional[UpdateL7LoadBalancerRequestCustomDomain]
            ``{hostname}`` to set (https only), ``None`` to clear.

        rules : typing.Optional[typing.Sequence[LoadBalancerRule]]
            Path rules (see create).

        policy : typing.Optional[typing.Dict[str, typing.Any]]
            ``{timeout_ms (100-300000), retries: {attempts 1-10, on [...], per_retry_timeout_ms 100-120000},
            proxy_protocol_enabled}``. Not yet part of the published API contract; behaviour may change.

        health_check : typing.Optional[typing.Dict[str, typing.Any]]
            ``{active: {type http|https|tcp, path (not for tcp), interval_ms, timeout_ms (100-120000),
            healthy_threshold, unhealthy_threshold (1-20)}, passive: {...}}``. Not sent unless given (the portal's
            form default is an http check of /health every 10 s). Not yet part of the published API contract;
            behaviour may change.

        observability : typing.Optional[typing.Dict[str, typing.Any]]
            ``{logs_enabled: bool}``. Not yet part of the published API contract; behaviour may change.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        LoadBalancer
        """
        return await run_async(self._raw_client._client_wrapper, nw.update_load_balancer("l7", **{**clean_kwargs(locals()), "custom_domain": custom_domain}), request_options)

    async def get_load_balancer_status(
        self, load_balancer_id: str, *, workspace_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> LoadBalancerStatusResponse:
        """
        Parameters
        ----------
        load_balancer_id : str
            Load balancer ID.

        workspace_id : str
            The workspace ID to scope this request to.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        LoadBalancerStatusResponse
            Load balancer status returned successfully.

        Examples
        --------
        import asyncio

        from ibee import AsyncIbee

        client = AsyncIbee(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.load_balancers.get_load_balancer_status(
                load_balancer_id="load_balancer_id",
                workspace_id="workspace_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_load_balancer_status(
            load_balancer_id, workspace_id=workspace_id, request_options=request_options
        )
        return _response.data
